## Data Processing

In [1]:
import pandas as pd

df_ff6 = pd.read_csv('/content/FF6.csv')
df_cay = pd.read_csv('/content/cay_index.csv')
df_market = pd.read_csv('/content/Market-Returns-Cleaned.csv')
df_consumption = pd.read_csv('/content/Consumption-Cleaned.csv')
df_ff6_factors = pd.read_csv('/content/FF6_Factors.csv')
df_income = pd.read_csv('/content/Income-Cleaned.csv')
df_risk_free = pd.read_csv('/content/Risk-Free-Cleaned.csv')

print("FF6.csv:")
display(df_ff6.head())
df_ff6.info()

print("\ncay_index.csv:")
display(df_cay.head())
df_cay.info()

print("\nMarket-Returns-Cleaned.csv:")
display(df_market.head())
df_market.info()

print("\nConsumption-Cleaned.csv:")
display(df_consumption.head())
df_consumption.info()

print("\nFF6_Factors.csv:")
display(df_ff6_factors.head())
df_ff6_factors.info()

print("\nIncome-Cleaned.csv:")
display(df_income.head())
df_income.info()

print("\nRisk-Free-Cleaned.csv:")
display(df_risk_free.head())
df_risk_free.info()

FF6.csv:

,month,Portfolios BV returns (%),Portfolios BN returns (%),Portfolios BG returns (%),Portfolios SV returns (%),Portfolios SN returns (%),Portfolios SG returns (%)
0,Apr-14,NaN,0.262471,0.172784,13.215249,6.550439,5.111012
1,May-14,NaN,23.102455,7.275463,27.552673,24.288677,15.810411
2,Jun-14,NaN,1.873951,7.745938,18.652457,16.839867,13.023586
3,Jul-14,NaN,-3.014671,1.413907,-7.500655,-2.044578,2.165995
4,Aug-14,NaN,-2.396891,4.203748,-0.729519,4.765247,4.484203

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      132 non-null    object
 1   Portfolios BV returns (%)  115 non-null    float64
 2   Portfolios BN returns (%)  132 non-null    float64
 3   Portfolios BG returns (%)  132 non-null    float64
 4   Portfolios SV returns (%)  132 non-null    float64
 5   Portfolios SN returns (%)  132 non-null    float64
 6   Portfolios SG returns (%)  132 non-null    float64
dtypes: float64(6), object(1)
memory usage: 7.3+ KB

cay_index.csv:

   month_x       cay
0  2014-04  0.057466
1  2014-05 -0.025694
2  2014-06  0.027865
3  2014-07  0.094101
4  2014-08  0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   month_x  132 non-null    object
 1   cay      132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Market-Returns-Cleaned.csv:

,month,market_return,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122
0,Apr-14,-0.006342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,May-14,0.008682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jun-14,0.015540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jul-14,-0.004266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aug-14,0.001078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Columns: 123 entries, month  to Unnamed: 122
dtypes: float64(122), object(1)
memory usage: 127.0+ KB

Consumption-Cleaned.csv:

     month  weighted_avg_consumption
0  2014-04               7208.683747
1  2014-05               7005.035044
2  2014-06               7311.807185
3  2014-07               8051.858683
4  2014-08               7449.553517

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   month                     132 non-null    object
 1   weighted_avg_consumption  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

FF6_Factors.csv:

      Date       SMB        HML       WML        MF        RF
0  2014-04  5.592209   7.810347 -3.415147  0.013121  0.701553
1  2014-05  4.340620  10.499133 -8.697000  9.950842  0.693805
2  2014-06  9.644133   5.182859  2.562922  6.929204  0.699993
3  2014-07  0.896284  -9.319494 -1.127898 -0.233564  0.700633
4  2014-08  3.732569  -4.896134  5.494075  2.452235  0.637590

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    132 non-null    object
 1   SMB     132 non-null    float64
 2   HML     132 non-null    float64
 3   WML     132 non-null    float64
 4   MF      132 non-null    float64
 5   RF      132 non-null    float64
dtypes: float64(5), object(1)
memory usage: 6.3+ KB

Income-Cleaned.csv:

     month  national_weighted_avg_income
0  2014-04                   12811.15146
1  2014-05                   14071.83162
2  2014-06                   13803.13302
3  2014-07                   14442.45259
4  2014-08                   13169.36297

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   month                         132 non-null    object
 1   national_weighted_avg_income  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Risk-Free-Cleaned.csv:

     month   Yeild
0  2014-04  8.8550
1  2014-05  8.6456
2  2014-06  8.5619
3  2014-07  8.6456
4  2014-08  8.6038

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   132 non-null    object
 1   Yeild   132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

In [2]:
df_ff6['month'] = pd.to_datetime(df_ff6['month'], format='%b-%y')
df_ff6_factors['Date'] = pd.to_datetime(df_ff6_factors['Date'])
df_market['month '] = pd.to_datetime(df_market['month '], format='%b-%y')
df_risk_free['month'] = pd.to_datetime(df_risk_free['month'])
df_cay['month_x'] = pd.to_datetime(df_cay['month_x'])
df_consumption['month'] = pd.to_datetime(df_consumption['month'])
df_income['month'] = pd.to_datetime(df_income['month'])

merged_df = pd.merge(df_ff6, df_risk_free, left_on='month', right_on='month', how='inner')
merged_df = pd.merge(merged_df, df_ff6_factors, left_on='month', right_on='Date', how='inner')
merged_df = pd.merge(merged_df, df_market[['month ', 'market_return']], left_on='month', right_on='month ', how='inner')

portfolio_cols = ['Portfolios BV returns (%)', 'Portfolios BN returns (%)', 'Portfolios BG returns (%)', 'Portfolios SV returns (%)', 'Portfolios SN returns (%)', 'Portfolios SG returns (%)']
for col in portfolio_cols:
    merged_df[f'{col}_excess'] = merged_df[col] - merged_df['Yeild']

merged_df['market_return_excess'] = merged_df['market_return'] - merged_df['Yeild']

merged_df.rename(columns={'Date': 'date', 'month_x': 'date', 'month': 'date', 'month ': 'date',
                          'Portfolios BV returns (%)_excess': 'BV_excess_return',
                          'Portfolios BN returns (%)_excess': 'BN_excess_return',
                          'Portfolios BG returns (%)_excess': 'BG_excess_return',
                          'Portfolios SV returns (%)_excess': 'SV_excess_return',
                          'Portfolios SN returns (%)_excess': 'SN_excess_return',
                          'Portfolios SG returns (%)_excess': 'SG_excess_return',
                          'market_excess_return': 'market_excess_return',
                          'SMB': 'smb', 'HML': 'hml', 'WML': 'wml', 'MF': 'mf', 'RF': 'rf',
                          'weighted_avg_consumption': 'consumption',
                          'national_weighted_avg_income': 'income',
                          'cay': 'cay_index'}, inplace=True)


columns_to_drop = portfolio_cols + ['market_return', 'Yeild']
merged_df.drop(columns=columns_to_drop, inplace=True)

display(merged_df.head())
merged_df.info()

,date,date,smb,hml,wml,mf,rf,date,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_return_excess
0,2014-04-01,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,2014-04-01,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342
1,2014-05-01,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,2014-05-01,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918
2,2014-06-01,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,2014-06-01,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360
3,2014-07-01,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,2014-07-01,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866
4,2014-08-01,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,2014-08-01,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  132 non-null    datetime64[ns]
 1   date                  132 non-null    datetime64[ns]
 2   smb                   132 non-null    float64
 3   hml                   132 non-null    float64
 4   wml                   132 non-null    float64
 5   mf                    132 non-null    float64
 6   rf                    132 non-null    float64
 7   date                  132 non-null    datetime64[ns]
 8   BV_excess_return      115 non-null    float64
 9   BN_excess_return      132 non-null    float64
 10  BG_excess_return      132 non-null    float64
 11  SV_excess_return      132 non-null    float64
 12  SN_excess_return      132 non-null    float64
 13  SG_excess_return      132 non-null    float64
 14  market_return_excess  132 non-null    float64
dtypes: datetime64[ns](3), float64(12)
memory usage: 15.6 KB

In [3]:
df_income.rename(columns={'month': 'date'}, inplace=True)
df_consumption.rename(columns={'month': 'date'}, inplace=True)

merged_df = merged_df.loc[:,~merged_df.columns.duplicated()]

merged_df = pd.merge(merged_df, df_income, on='date', how='inner')
merged_df = pd.merge(merged_df, df_consumption, on='date', how='inner')

print(merged_df.columns)

merged_df['income_growth'] = merged_df['national_weighted_avg_income'].pct_change() * 100
merged_df['consumption_growth'] = merged_df['weighted_avg_consumption'].pct_change() * 100

display(merged_df.head())

Index(['date', 'smb', 'hml', 'wml', 'mf', 'rf', 'BV_excess_return',
       'BN_excess_return', 'BG_excess_return', 'SV_excess_return',
       'SN_excess_return', 'SG_excess_return', 'market_return_excess',
       'national_weighted_avg_income', 'weighted_avg_consumption'],
      dtype='object')

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_return_excess,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325

In [4]:
merged_df = pd.merge(merged_df, df_cay, left_on='date', right_on='month_x', how='inner')

display(merged_df.head())
merged_df.info()

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_return_excess,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN,2014-04-01,0.057466
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309,2014-06-01,0.027865
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321,2014-07-01,0.094101
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          132 non-null    datetime64[ns]
 1   smb                           132 non-null    float64
 2   hml                           132 non-null    float64
 3   wml                           132 non-null    float64
 4   mf                            132 non-null    float64
 5   rf                            132 non-null    float64
 6   BV_excess_return              115 non-null    float64
 7   BN_excess_return              132 non-null    float64
 8   BG_excess_return              132 non-null    float64
 9   SV_excess_return              132 non-null    float64
 10  SN_excess_return              132 non-null    float64
 11  SG_excess_return              132 non-null    float64
 12  market_return_excess          132 non-null    float64
 13  national_weighted_avg_income  132 non-null    float64
 14  weighted_avg_consumption      132 non-null    float64
 15  income_growth                 131 non-null    float64
 16  consumption_growth            131 non-null    float64
 17  month_x                       132 non-null    datetime64[ns]
 18  cay                           132 non-null    float64
dtypes: datetime64[ns](2), float64(17)
memory usage: 19.7 KB

In [5]:
print(merged_df.columns)

Index(['date', 'smb', 'hml', 'wml', 'mf', 'rf', 'BV_excess_return',
       'BN_excess_return', 'BG_excess_return', 'SV_excess_return',
       'SN_excess_return', 'SG_excess_return', 'market_return_excess',
       'national_weighted_avg_income', 'weighted_avg_consumption',
       'income_growth', 'consumption_growth', 'month_x', 'cay'],
      dtype='object')

In [6]:
macro_vars = ['income_growth', 'consumption_growth', 'cay']

for var in macro_vars:
    mean = merged_df[var].mean()
    std = merged_df[var].std()
    merged_df[f'{var}_standardized'] = (merged_df[var] - mean) / std

display(merged_df.head())

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,...,market_return_excess,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay,income_growth_standardized,consumption_growth_standardized,cay_standardized
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,...,-8.861342,12811.15146,7208.683747,NaN,NaN,2014-04-01,0.057466,NaN,NaN,0.278844
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,...,-8.636918,14071.83162,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694,1.708192,-0.349998,-0.124676
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,...,-8.546360,13803.13302,7311.807185,-1.909479,4.379309,2014-06-01,0.027865,-0.534120,0.271423,0.135212
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,...,-8.649866,14442.45259,8051.858683,4.631699,10.121321,2014-07-01,0.094101,0.714170,0.766707,0.456614
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,...,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530,-1.851922,-0.751545,0.361647

In [7]:
merged_df['market_excess_return_x_cay'] = merged_df['market_return_excess'] * merged_df['cay_standardized']
#merged_df['human_capital_return_x_cay'] = merged_df['human_capital_return'] * merged_df['cay_standardized']
merged_df['consumption_growth_x_cay'] = merged_df['consumption_growth'] * merged_df['cay_standardized']

display(merged_df.head())

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,...,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay,income_growth_standardized,consumption_growth_standardized,cay_standardized,market_excess_return_x_cay,consumption_growth_x_cay
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,...,7208.683747,NaN,NaN,2014-04-01,0.057466,NaN,NaN,0.278844,-2.470932,NaN
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,...,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694,1.708192,-0.349998,-0.124676,1.076812,0.352214
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,...,7311.807185,-1.909479,4.379309,2014-06-01,0.027865,-0.534120,0.271423,0.135212,-1.155574,0.592137
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,...,8051.858683,4.631699,10.121321,2014-07-01,0.094101,0.714170,0.766707,0.456614,-3.949649,4.621536
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,...,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530,-1.851922,-0.751545,0.361647,-3.111151,-2.705239

## Model

In [18]:
import statsmodels.api as sm
import pandas as pd

portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

portfolio_betas = {}
time_series_residuals = pd.DataFrame(index=merged_df.index) # DataFrame to store residuals

X_ts = sm.add_constant(merged_df['market_return_excess'])

for portfolio_col in portfolio_excess_return_cols:
    y_ts = merged_df[portfolio_col]
    # Drop rows with NaN values in the current portfolio's excess return
    valid_indices_ts = y_ts.dropna().index
    y_cleaned_ts = y_ts.loc[valid_indices_ts]
    X_cleaned_ts = X_ts.loc[valid_indices_ts]

    model_ts = sm.OLS(y_cleaned_ts, X_cleaned_ts)
    results_ts = model_ts.fit()
    portfolio_betas[portfolio_col] = results_ts.params['market_return_excess']

    # Store residuals, reindexing to the original merged_df index to preserve NaN alignment
    residuals = results_ts.resid
    time_series_residuals[portfolio_col] = pd.Series(residuals, index=valid_indices_ts)

print("Estimated Betas for each portfolio:")
for portfolio, beta in portfolio_betas.items():
    print(f"{portfolio}: {beta:.4f}")

Estimated Betas for each portfolio:
BV_excess_return: 2.2070
BN_excess_return: 1.5345
BG_excess_return: 1.2570
SV_excess_return: 1.6692
SN_excess_return: 1.2914
SG_excess_return: 1.2467

In [9]:
import statsmodels.api as sm
import numpy as np

betas_df = pd.DataFrame.from_dict(portfolio_betas, orient='index', columns=['market_excess_return'])
betas_df = betas_df.T
betas_df = sm.add_constant(betas_df)

lambda_estimates = []

portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

for index, row in merged_df.iterrows():
    y_cs = row[portfolio_excess_return_cols]
    # Align y_cs with the transposed betas_df
    y_cs_aligned = y_cs.reindex(betas_df.columns)

    # Drop NaN values from y_cs_aligned and corresponding rows from betas_df
    valid_indices = y_cs_aligned.dropna().index

    # Ensure there are at least 2 valid data points for regression (for intercept and slope)
    if len(valid_indices) >= 2:
        y_cs_cleaned = y_cs_aligned.loc[valid_indices].astype(float)
        betas_df_cleaned = betas_df.loc[:, valid_indices].astype(float)

        try:
            model_cs = sm.OLS(y_cs_cleaned, betas_df_cleaned.T)
            results_cs = model_cs.fit()
            # Ensure the number of parameters is 2 before appending
            if len(results_cs.params) == 2:
                lambda_estimates.append(results_cs.params.tolist())
            else:
                lambda_estimates.append([np.nan, np.nan])
        except Exception as e:
            # Handle potential errors during regression
            print(f"Regression error at index {index}: {e}")
            lambda_estimates.append([np.nan, np.nan])
    else:
        # Append NaNs if regression cannot be performed
        lambda_estimates.append([np.nan, np.nan])


lambda_df = pd.DataFrame(lambda_estimates, columns=['lambda_0', 'lambda_market'])
display(lambda_df.head())

   lambda_0  lambda_market
0       NaN            NaN
1       NaN            NaN
2       NaN            NaN
3       NaN            NaN
4       NaN            NaN

In [10]:
import statsmodels.api as sm
import numpy as np

betas_df = pd.DataFrame.from_dict(portfolio_betas, orient='index', columns=['market_excess_return'])
betas_df = betas_df.T
betas_df = sm.add_constant(betas_df)

lambda_estimates = []

portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

for index, row in merged_df.iterrows():
    y_cs = row[portfolio_excess_return_cols]
    # Align y_cs with the transposed betas_df
    y_cs_aligned = y_cs.reindex(betas_df.columns)

    # Drop NaN values from y_cs_aligned and corresponding rows from betas_df
    valid_indices = y_cs_aligned.dropna().index

    # Ensure there are at least 2 valid data points for regression (for intercept and slope)
    if len(valid_indices) >= 2:
        y_cs_cleaned = y_cs_aligned.loc[valid_indices].astype(float)
        betas_df_cleaned = betas_df.loc[:, valid_indices].astype(float)

        # Debugging prints
        if index < 5: # Print for first 5 iterations
            print(f"Index: {index}")
            print(f"y_cs_cleaned shape: {y_cs_cleaned.shape}")
            print(f"betas_df_cleaned.T shape: {betas_df_cleaned.T.shape}")
            print(f"y_cs_cleaned has NaNs: {y_cs_cleaned.isnull().any()}")
            print(f"betas_df_cleaned.T has NaNs: {betas_df_cleaned.T.isnull().any().any()}")


        try:
            model_cs = sm.OLS(y_cs_cleaned, betas_df_cleaned.T)
            results_cs = model_cs.fit()
            # Ensure the number of parameters is 2 before appending
            if len(results_cs.params) == 2:
                lambda_estimates.append(results_cs.params.tolist())
            else:
                lambda_estimates.append([np.nan, np.nan])
        except Exception as e:
            # Handle potential errors during regression
            print(f"Regression error at index {index}: {e}")
            lambda_estimates.append([np.nan, np.nan])
    else:
        # Append NaNs if regression cannot be performed
        lambda_estimates.append([np.nan, np.nan])


lambda_df = pd.DataFrame(lambda_estimates, columns=['lambda_0', 'lambda_market'])
display(lambda_df.head())

Index: 0
y_cs_cleaned shape: (5,)
betas_df_cleaned.T shape: (5, 1)
y_cs_cleaned has NaNs: False
betas_df_cleaned.T has NaNs: False
Index: 1
y_cs_cleaned shape: (5,)
betas_df_cleaned.T shape: (5, 1)
y_cs_cleaned has NaNs: False
betas_df_cleaned.T has NaNs: False
Index: 2
y_cs_cleaned shape: (5,)
betas_df_cleaned.T shape: (5, 1)
y_cs_cleaned has NaNs: False
betas_df_cleaned.T has NaNs: False
Index: 3
y_cs_cleaned shape: (5,)
betas_df_cleaned.T shape: (5, 1)
y_cs_cleaned has NaNs: False
betas_df_cleaned.T has NaNs: False
Index: 4
y_cs_cleaned shape: (5,)
betas_df_cleaned.T shape: (5, 1)
y_cs_cleaned has NaNs: False
betas_df_cleaned.T has NaNs: False

   lambda_0  lambda_market
0       NaN            NaN
1       NaN            NaN
2       NaN            NaN
3       NaN            NaN
4       NaN            NaN

In [11]:
import statsmodels.api as sm
import numpy as np

betas_df = pd.DataFrame.from_dict(portfolio_betas, orient='index', columns=['market_excess_return'])
betas_df = sm.add_constant(betas_df) # Add constant to the betas DataFrame

lambda_estimates = []

portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

for index, row in merged_df.iterrows():
    y_cs = row[portfolio_excess_return_cols]

    # Drop NaN values from y_cs and get the corresponding betas
    valid_portfolios = y_cs.dropna().index
    y_cs_cleaned = y_cs.loc[valid_portfolios].astype(float)

    # Select the betas corresponding to the valid portfolios
    betas_for_cs = betas_df.loc[valid_portfolios].astype(float)


    # Ensure there are at least 2 valid data points for regression (for intercept and slope) and that betas_for_cs is not empty
    if len(valid_portfolios) >= 2 and not betas_for_cs.empty:
        try:
            model_cs = sm.OLS(y_cs_cleaned, betas_for_cs) # Use betas_for_cs directly as the exogenous variable
            results_cs = model_cs.fit()
            # Ensure the number of parameters is 2 before appending
            if len(results_cs.params) == 2:
                lambda_estimates.append(results_cs.params.tolist())
            else:
                lambda_estimates.append([np.nan, np.nan])
        except Exception as e:
            # Handle potential errors during regression
            print(f"Regression error at index {index}: {e}")
            lambda_estimates.append([np.nan, np.nan])
    else:
        # Append NaNs if regression cannot be performed
        lambda_estimates.append([np.nan, np.nan])


lambda_df = pd.DataFrame(lambda_estimates, columns=['lambda_0', 'lambda_market'])
display(lambda_df.head())

    lambda_0  lambda_market
0 -23.682983      14.209812
1 -31.573370      30.386356
2  -0.318784       2.417583
3  15.762053     -18.720060
4  15.681436     -15.874026

In [12]:
lambda_0_mean = lambda_df['lambda_0'].mean()
lambda_0_sem = lambda_df['lambda_0'].sem()
lambda_market_mean = lambda_df['lambda_market'].mean()
lambda_market_sem = lambda_df['lambda_market'].sem()

print(f"Mean of lambda_0: {lambda_0_mean:.4f}")
print(f"Standard Error of lambda_0: {lambda_0_sem:.4f}")
print(f"Mean of lambda_market: {lambda_market_mean:.4f}")
print(f"Standard Error of lambda_market: {lambda_market_sem:.4f}")

Mean of lambda_0: -5.3266
Standard Error of lambda_0: 0.8327
Mean of lambda_market: 0.6882
Standard Error of lambda_market: 0.6286

In [13]:
import numpy as np

# 1. Calculate the mean vector and covariance matrix of the factor returns
# In this case, the only factor is market excess return.
mu_f = merged_df['market_return_excess'].mean()
# Corrected: Use var() for the variance of a single variable
Sigma_f = merged_df['market_return_excess'].var()

# 2. Calculate the Shanken correction factor
# The formula is (1 + mu_f' * inv(Sigma_f) * mu_f)
# For a single factor, this simplifies to (1 + mu_f^2 / Sigma_f)
shanken_correction_factor = (1 + (mu_f**2) / Sigma_f)

# 3. Multiply the squared standard errors of the Fama-MacBeth lambdas by the Shanken correction factor
lambda_0_shanken_variance = (lambda_0_sem**2) * shanken_correction_factor
lambda_market_shanken_variance = (lambda_market_sem**2) * shanken_correction_factor

# 4. Take the square root of the Shanken-corrected variances to get the Shanken-corrected standard errors
lambda_0_shanken_sem = np.sqrt(lambda_0_shanken_variance)
lambda_market_shanken_sem = np.sqrt(lambda_market_shanken_variance)

# 5. Calculate the t-statistics for the lambdas using the mean lambdas and the Shanken-corrected standard errors
lambda_0_shanken_tstat = lambda_0_mean / lambda_0_shanken_sem
lambda_market_shanken_tstat = lambda_market_mean / lambda_market_shanken_sem

# 6. Print the Shanken-corrected standard errors and t-statistics
print(f"Shanken-corrected Standard Error of lambda_0: {lambda_0_shanken_sem:.4f}")
print(f"Shanken-corrected t-statistic for lambda_0: {lambda_0_shanken_tstat:.4f}")
print(f"Shanken-corrected Standard Error of lambda_market: {lambda_market_shanken_sem:.4f}")
print(f"Shanken-corrected t-statistic for lambda_market: {lambda_market_shanken_tstat:.4f}")

Shanken-corrected Standard Error of lambda_0: 3.4162
Shanken-corrected t-statistic for lambda_0: -1.5592
Shanken-corrected Standard Error of lambda_market: 2.5787
Shanken-corrected t-statistic for lambda_market: 0.2669

In [14]:
import statsmodels.api as sm
import numpy as np

cs_r_squared_values = []

portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

betas_df = pd.DataFrame.from_dict(portfolio_betas, orient='index', columns=['market_excess_return'])
betas_df = sm.add_constant(betas_df)

for index, row in merged_df.iterrows():
    y_cs = row[portfolio_excess_return_cols]

    valid_portfolios = y_cs.dropna().index
    y_cs_cleaned = y_cs.loc[valid_portfolios].astype(float)

    betas_for_cs = betas_df.loc[valid_portfolios].astype(float)

    if len(valid_portfolios) >= 2 and not betas_for_cs.empty:
        try:
            model_cs = sm.OLS(y_cs_cleaned, betas_for_cs)
            results_cs = model_cs.fit()
            if len(results_cs.params) == 2:
                cs_r_squared_values.append(results_cs.rsquared)
            else:
                cs_r_squared_values.append(np.nan)
        except Exception as e:
            print(f"Regression error at index {index}: {e}")
            cs_r_squared_values.append(np.nan)
    else:
        cs_r_squared_values.append(np.nan)

average_cs_r_squared = np.nanmean(cs_r_squared_values)

print(f"Average Cross-Sectional R-squared: {average_cs_r_squared:.4f}")

Average Cross-Sectional R-squared: 0.3437

In [15]:
print(f"Mean lambda_market: {lambda_market_mean:.4f}")
print(f"Shanken-corrected t-statistic for lambda_market: {lambda_market_shanken_tstat:.4f}")
print(f"Mean lambda_0: {lambda_0_mean:.4f}")
print(f"Average cross-sectional R-squared: {average_cs_r_squared:.4f}")

Mean lambda_market: 0.6882
Shanken-corrected t-statistic for lambda_market: 0.2669
Mean lambda_0: -5.3266
Average cross-sectional R-squared: 0.3437

In [16]:
# 1. Calculate the mean of the actual excess returns for each portfolio
mean_excess_returns = merged_df[portfolio_excess_return_cols].mean()

# 2. Calculate the expected excess return for each portfolio
expected_excess_returns = {}
for portfolio, beta in portfolio_betas.items():
    expected_excess_returns[portfolio] = lambda_0_mean + lambda_market_mean * beta

# Convert to Series for easier calculations
expected_excess_returns = pd.Series(expected_excess_returns)

# 3. Calculate the pricing error for each portfolio
pricing_errors = mean_excess_returns - expected_excess_returns

print("Mean Actual Excess Returns:")
display(mean_excess_returns)
print("\nExpected Excess Returns:")
display(expected_excess_returns)
print("\nPricing Errors (Actual - Expected):")
display(pricing_errors)

Mean Actual Excess Returns:

BV_excess_return   -3.483671
BN_excess_return   -4.444721
BG_excess_return   -4.895233
SV_excess_return   -3.838605
SN_excess_return   -3.874357
SG_excess_return   -4.644875
dtype: float64

Expected Excess Returns:

BV_excess_return   -3.807793
BN_excess_return   -4.270537
BG_excess_return   -4.461516
SV_excess_return   -4.177863
SN_excess_return   -4.437876
SG_excess_return   -4.468607
dtype: float64

Pricing Errors (Actual - Expected):

BV_excess_return    0.324122
BN_excess_return   -0.174184
BG_excess_return   -0.433717
SV_excess_return    0.339258
SN_excess_return    0.563519
SG_excess_return   -0.176268
dtype: float64

In [17]:
import numpy as np
from scipy.stats import chi2

# 4. Calculate the aggregated mean pricing error (e.g., Root Mean Squared Pricing Error)
rmse_pricing_error = np.sqrt(np.mean(pricing_errors**2))

print(f"Root Mean Squared Pricing Error (RMSE): {rmse_pricing_error:.4f}")

SSPE = np.sum(pricing_errors**2)

N = len(portfolio_excess_return_cols)
K = 1 # Market factor

df_chi2 = N - K - 1 # Degrees of freedom

# We'll calculate a simpler measure first: the sum of squared pricing errors.
print(f"\nSum of Squared Pricing Errors (SSPE): {SSPE:.4f}")
avg_portfolio_variance = merged_df[portfolio_excess_return_cols].var().mean()

chi2_statistic = (pricing_errors**2 / pricing_errors.sem()).sum() if pricing_errors.sem() > 0 else np.nan

Root Mean Squared Pricing Error (RMSE): 0.3622

Sum of Squared Pricing Errors (SSPE): 0.7872

In [19]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy.stats import chi2

# Ensure time_series_residuals and pricing_errors are aligned and complete
# The BV_excess_return portfolio has some NaN values in its time-series residuals.
# To calculate the covariance matrix, we will drop rows where any residual is NaN.
# This means we will only use time periods where all portfolios have valid residuals.
# However, dropping rows with any NaN might remove too much data. A common practice
# is to use pairwise deletion for covariance, but for matrix inversion, it's better
# to have a consistent set of observations. Given the BV_excess_return column
# has 115 non-nulls out of 132, dropping rows with any NaN will result in 115 valid observations.

# Let's align the residuals and pricing errors.
# Identify portfolios that are present in both `time_series_residuals` and `pricing_errors`
common_portfolios = list(set(time_series_residuals.columns) & set(pricing_errors.index))

# Filter `time_series_residuals` to only include `common_portfolios`
cleaned_time_series_residuals = time_series_residuals[common_portfolios]

# Drop rows from `cleaned_time_series_residuals` that have *any* NaN across these common portfolios
# This ensures a consistent set of time periods for the covariance matrix calculation.
cleaned_time_series_residuals_no_nan = cleaned_time_series_residuals.dropna(how='any')

# Filter `pricing_errors` to only include `common_portfolios`
pricing_errors_for_chi2 = pricing_errors.loc[common_portfolios]

# Check if enough data remains after dropping NaNs
if len(cleaned_time_series_residuals_no_nan) < 2:
    print("Not enough valid time series observations after dropping NaNs to calculate covariance matrix.")
    chi2_statistic = np.nan
    df_chi2 = np.nan
    p_value = np.nan
else:
    # 1. Calculate the covariance matrix of the cleaned time-series residuals (S_e)
    # This is an N x N matrix where N is the number of portfolios being tested.
    S_e = cleaned_time_series_residuals_no_nan.cov()

    # Number of time periods (T) used for the residuals (after cleaning NaNs)
    T_actual = len(cleaned_time_series_residuals_no_nan)

    # Number of factors (K) - 1 for market factor in the second pass
    K = 1

    # Number of portfolios (N) being tested
    N_test = len(common_portfolios)

    # Ensure S_e is invertible
    try:
        # Invert the covariance matrix
        inv_S_e = pd.DataFrame(np.linalg.inv(S_e.values), columns=S_e.columns, index=S_e.index)

        # 2. Calculate the Chi-square statistic (Wald test) for pricing errors
        # Wald = T_actual * (pricing_errors_vector)' * inv(S_e) * (pricing_errors_vector)
        chi2_statistic = T_actual * pricing_errors_for_chi2.values.T @ inv_S_e.values @ pricing_errors_for_chi2.values

        # 3. Degrees of freedom for the test
        # For a Wald test on N pricing errors, with K factors and an intercept (lambda_0) in the cross-sectional regression,
        # the degrees of freedom are N - (number of parameters estimated in CS regression) = N - (K + 1)
        df_chi2 = N_test - K - 1

        if df_chi2 <= 0:
            print(f"Degrees of freedom ({df_chi2}) is not positive. Cannot perform Chi-square test meaningfully.")
            p_value = np.nan
        else:
            # 4. Calculate the p-value
            p_value = 1 - chi2.cdf(chi2_statistic, df_chi2)

    except np.linalg.LinAlgError:
        print("Covariance matrix of time-series residuals is singular, cannot invert. Cannot perform Chi-square test.")
        chi2_statistic = np.nan
        df_chi2 = np.nan
        p_value = np.nan

print(f"Chi-square statistic (Wald test) for pricing errors: {chi2_statistic:.4f}")
print(f"Degrees of freedom: {df_chi2}")
print(f"P-value: {p_value:.4f}")

print("\nInterpretation:")
print("The null hypothesis of the Wald test is that all pricing errors (alphas) are jointly zero.")
print("A small p-value (typically < 0.05) would lead to the rejection of the null hypothesis,")
print("suggesting that the model does not fully explain the cross-section of expected returns.")

Chi-square statistic (Wald test) for pricing errors: 29.2671
Degrees of freedom: 4
P-value: 0.0000

Interpretation:
The null hypothesis of the Wald test is that all pricing errors (alphas) are jointly zero.
A small p-value (typically < 0.05) would lead to the rejection of the null hypothesis,
suggesting that the model does not fully explain the cross-section of expected returns.

### Interpretation of Pricing Errors

The **Root Mean Squared Pricing Error (RMSE)** provides a single, aggregate measure of how well the model prices the portfolios. A smaller RMSE indicates a better fit, meaning the model's expected returns are closer to the actual mean returns.

The **Sum of Squared Pricing Errors (SSPE)** is another aggregate measure, emphasizing larger individual pricing errors. While both provide insights into the model's overall fit, interpreting whether these values are 'good' or 'bad' often requires comparison to other models or benchmarks.

**Note on Chi-square statistic**: A formal Chi-square (or GMM J-test) for pricing errors in a Fama-MacBeth framework requires the full covariance matrix of the pricing errors, which is derived from the GMM estimation process. The current implementation of Fama-MacBeth does not directly provide this. Therefore, a rigorous Chi-square test with a p-value cannot be performed with the current output. The Root Mean Squared Pricing Error (RMSE) and Sum of Squared Pricing Errors (SSPE) serve as practical aggregate measures of the model's ability to explain the cross-section of returns.