## Data Processing

In [1]:
import pandas as pd

df_ff6 = pd.read_csv('/content/FF6.csv')
df_cay = pd.read_csv('/content/cay_index.csv')
df_market = pd.read_csv('/content/Market-Returns-Cleaned.csv')
df_consumption = pd.read_csv('/content/Consumption-Cleaned.csv')
df_ff6_factors = pd.read_csv('/content/FF6_Factors.csv')
df_income = pd.read_csv('/content/Income-Cleaned.csv')
df_risk_free = pd.read_csv('/content/Risk-Free-Cleaned.csv')

print("FF6.csv:")
display(df_ff6.head())
df_ff6.info()

print("\ncay_index.csv:")
display(df_cay.head())
df_cay.info()

print("\nMarket-Returns-Cleaned.csv:")
display(df_market.head())
df_market.info()

print("\nConsumption-Cleaned.csv:")
display(df_consumption.head())
df_consumption.info()

print("\nFF6_Factors.csv:")
display(df_ff6_factors.head())
df_ff6_factors.info()

print("\nIncome-Cleaned.csv:")
display(df_income.head())
df_income.info()

print("\nRisk-Free-Cleaned.csv:")
display(df_risk_free.head())
df_risk_free.info()

FF6.csv:

,month,Portfolios BV returns (%),Portfolios BN returns (%),Portfolios BG returns (%),Portfolios SV returns (%),Portfolios SN returns (%),Portfolios SG returns (%)
0,Apr-14,NaN,0.262471,0.172784,13.215249,6.550439,5.111012
1,May-14,NaN,23.102455,7.275463,27.552673,24.288677,15.810411
2,Jun-14,NaN,1.873951,7.745938,18.652457,16.839867,13.023586
3,Jul-14,NaN,-3.014671,1.413907,-7.500655,-2.044578,2.165995
4,Aug-14,NaN,-2.396891,4.203748,-0.729519,4.765247,4.484203

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      132 non-null    object
 1   Portfolios BV returns (%)  115 non-null    float64
 2   Portfolios BN returns (%)  132 non-null    float64
 3   Portfolios BG returns (%)  132 non-null    float64
 4   Portfolios SV returns (%)  132 non-null    float64
 5   Portfolios SN returns (%)  132 non-null    float64
 6   Portfolios SG returns (%)  132 non-null    float64
dtypes: float64(6), object(1)
memory usage: 7.3+ KB

cay_index.csv:

   month_x       cay
0  2014-04  0.057466
1  2014-05 -0.025694
2  2014-06  0.027865
3  2014-07  0.094101
4  2014-08  0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   month_x  132 non-null    object
 1   cay      132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Market-Returns-Cleaned.csv:

,month,market_return,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122
0,Apr-14,-0.006342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,May-14,0.008682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jun-14,0.015540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jul-14,-0.004266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aug-14,0.001078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Columns: 123 entries, month  to Unnamed: 122
dtypes: float64(122), object(1)
memory usage: 127.0+ KB

Consumption-Cleaned.csv:

     month  weighted_avg_consumption
0  2014-04               7208.683747
1  2014-05               7005.035044
2  2014-06               7311.807185
3  2014-07               8051.858683
4  2014-08               7449.553517

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   month                     132 non-null    object
 1   weighted_avg_consumption  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

FF6_Factors.csv:

      Date       SMB        HML       WML        MF        RF
0  2014-04  5.592209   7.810347 -3.415147  0.013121  0.701553
1  2014-05  4.340620  10.499133 -8.697000  9.950842  0.693805
2  2014-06  9.644133   5.182859  2.562922  6.929204  0.699993
3  2014-07  0.896284  -9.319494 -1.127898 -0.233564  0.700633
4  2014-08  3.732569  -4.896134  5.494075  2.452235  0.637590

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    132 non-null    object
 1   SMB     132 non-null    float64
 2   HML     132 non-null    float64
 3   WML     132 non-null    float64
 4   MF      132 non-null    float64
 5   RF      132 non-null    float64
dtypes: float64(5), object(1)
memory usage: 6.3+ KB

Income-Cleaned.csv:

     month  national_weighted_avg_income
0  2014-04                   12811.15146
1  2014-05                   14071.83162
2  2014-06                   13803.13302
3  2014-07                   14442.45259
4  2014-08                   13169.36297

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   month                         132 non-null    object
 1   national_weighted_avg_income  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Risk-Free-Cleaned.csv:

     month   Yeild
0  2014-04  8.8550
1  2014-05  8.6456
2  2014-06  8.5619
3  2014-07  8.6456
4  2014-08  8.6038

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   132 non-null    object
 1   Yeild   132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

In [4]:
df_ff6['month'] = pd.to_datetime(df_ff6['month'], format='%b-%y')
df_ff6_factors['Date'] = pd.to_datetime(df_ff6_factors['Date'])
df_market['month '] = pd.to_datetime(df_market['month '], format='%b-%y')
df_risk_free['month'] = pd.to_datetime(df_risk_free['month'])
df_cay['month_x'] = pd.to_datetime(df_cay['month_x'])
df_consumption['month'] = pd.to_datetime(df_consumption['month'])
df_income['month'] = pd.to_datetime(df_income['month'])

merged_df = pd.merge(df_ff6, df_risk_free, left_on='month', right_on='month', how='inner')
merged_df = pd.merge(merged_df, df_ff6_factors, left_on='month', right_on='Date', how='inner')
merged_df = pd.merge(merged_df, df_market[['month ', 'market_return']], left_on='month', right_on='month ', how='inner')

portfolio_cols = ['Portfolios BV returns (%)', 'Portfolios BN returns (%)', 'Portfolios BG returns (%)', 'Portfolios SV returns (%)', 'Portfolios SN returns (%)', 'Portfolios SG returns (%)']
for col in portfolio_cols:
    merged_df[f'{col}_excess'] = merged_df[col] - merged_df['Yeild']

merged_df['market_return_excess'] = merged_df['market_return'] - merged_df['Yeild']

merged_df.rename(columns={'Date': 'date', 'month_x': 'date', 'month': 'date', 'month ': 'date',
                          'Portfolios BV returns (%)_excess': 'BV_excess_return',
                          'Portfolios BN returns (%)_excess': 'BN_excess_return',
                          'Portfolios BG returns (%)_excess': 'BG_excess_return',
                          'Portfolios SV returns (%)_excess': 'SV_excess_return',
                          'Portfolios SN returns (%)_excess': 'SN_excess_return',
                          'Portfolios SG returns (%)_excess': 'SG_excess_return',
                          'market_return_excess': 'market_excess_return',
                          'SMB': 'smb', 'HML': 'hml', 'WML': 'wml', 'MF': 'mf', 'RF': 'rf',
                          'weighted_avg_consumption': 'consumption',
                          'national_weighted_avg_income': 'income',
                          'cay': 'cay_index'}, inplace=True)


columns_to_drop = portfolio_cols + ['market_return', 'Yeild']
merged_df.drop(columns=columns_to_drop, inplace=True)

display(merged_df.head())
merged_df.info()

,date,date,smb,hml,wml,mf,rf,date,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return
0,2014-04-01,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,2014-04-01,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342
1,2014-05-01,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,2014-05-01,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918
2,2014-06-01,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,2014-06-01,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360
3,2014-07-01,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,2014-07-01,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866
4,2014-08-01,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,2014-08-01,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  132 non-null    datetime64[ns]
 1   date                  132 non-null    datetime64[ns]
 2   smb                   132 non-null    float64
 3   hml                   132 non-null    float64
 4   wml                   132 non-null    float64
 5   mf                    132 non-null    float64
 6   rf                    132 non-null    float64
 7   date                  132 non-null    datetime64[ns]
 8   BV_excess_return      115 non-null    float64
 9   BN_excess_return      132 non-null    float64
 10  BG_excess_return      132 non-null    float64
 11  SV_excess_return      132 non-null    float64
 12  SN_excess_return      132 non-null    float64
 13  SG_excess_return      132 non-null    float64
 14  market_excess_return  132 non-null    float64
dtypes: datetime64[ns](3), float64(12)
memory usage: 15.6 KB

In [5]:
df_income.rename(columns={'month': 'date'}, inplace=True)
df_consumption.rename(columns={'month': 'date'}, inplace=True)

merged_df = merged_df.loc[:,~merged_df.columns.duplicated()]

merged_df = pd.merge(merged_df, df_income, on='date', how='inner')
merged_df = pd.merge(merged_df, df_consumption, on='date', how='inner')

print(merged_df.columns)

merged_df['income_growth'] = merged_df['national_weighted_avg_income'].pct_change() * 100
merged_df['consumption_growth'] = merged_df['weighted_avg_consumption'].pct_change() * 100

display(merged_df.head())

Index(['date', 'smb', 'hml', 'wml', 'mf', 'rf', 'BV_excess_return',
       'BN_excess_return', 'BG_excess_return', 'SV_excess_return',
       'SN_excess_return', 'SG_excess_return', 'market_excess_return',
       'national_weighted_avg_income', 'weighted_avg_consumption'],
      dtype='object')

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325

In [6]:
merged_df = pd.merge(merged_df, df_cay, left_on='date', right_on='month_x', how='inner')

display(merged_df.head())
merged_df.info()

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN,2014-04-01,0.057466
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309,2014-06-01,0.027865
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321,2014-07-01,0.094101
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          132 non-null    datetime64[ns]
 1   smb                           132 non-null    float64
 2   hml                           132 non-null    float64
 3   wml                           132 non-null    float64
 4   mf                            132 non-null    float64
 5   rf                            132 non-null    float64
 6   BV_excess_return              115 non-null    float64
 7   BN_excess_return              132 non-null    float64
 8   BG_excess_return              132 non-null    float64
 9   SV_excess_return              132 non-null    float64
 10  SN_excess_return              132 non-null    float64
 11  SG_excess_return              132 non-null    float64
 12  market_excess_return          132 non-null    float64
 13  national_weighted_avg_income  132 non-null    float64
 14  weighted_avg_consumption      132 non-null    float64
 15  income_growth                 131 non-null    float64
 16  consumption_growth            131 non-null    float64
 17  month_x                       132 non-null    datetime64[ns]
 18  cay                           132 non-null    float64
dtypes: datetime64[ns](2), float64(17)
memory usage: 19.7 KB

In [7]:
print(merged_df.columns)

Index(['date', 'smb', 'hml', 'wml', 'mf', 'rf', 'BV_excess_return',
       'BN_excess_return', 'BG_excess_return', 'SV_excess_return',
       'SN_excess_return', 'SG_excess_return', 'market_excess_return',
       'national_weighted_avg_income', 'weighted_avg_consumption',
       'income_growth', 'consumption_growth', 'month_x', 'cay'],
      dtype='object')

In [8]:
macro_vars = ['income_growth', 'consumption_growth', 'cay']

for var in macro_vars:
    mean = merged_df[var].mean()
    std = merged_df[var].std()
    merged_df[f'{var}_standardized'] = (merged_df[var] - mean) / std

display(merged_df.head())

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,...,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay,income_growth_standardized,consumption_growth_standardized,cay_standardized
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,...,-8.861342,12811.15146,7208.683747,NaN,NaN,2014-04-01,0.057466,NaN,NaN,0.278844
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,...,-8.636918,14071.83162,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694,1.708192,-0.349998,-0.124676
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,...,-8.546360,13803.13302,7311.807185,-1.909479,4.379309,2014-06-01,0.027865,-0.534120,0.271423,0.135212
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,...,-8.649866,14442.45259,8051.858683,4.631699,10.121321,2014-07-01,0.094101,0.714170,0.766707,0.456614
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,...,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530,-1.851922,-0.751545,0.361647

In [9]:
merged_df['market_excess_return_x_cay'] = merged_df['market_excess_return'] * merged_df['cay_standardized']
#merged_df['human_capital_return_x_cay'] = merged_df['human_capital_return'] * merged_df['cay_standardized']
merged_df['consumption_growth_x_cay'] = merged_df['consumption_growth'] * merged_df['cay_standardized']

display(merged_df.head())

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,...,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay,income_growth_standardized,consumption_growth_standardized,cay_standardized,market_excess_return_x_cay,consumption_growth_x_cay
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,...,7208.683747,NaN,NaN,2014-04-01,0.057466,NaN,NaN,0.278844,-2.470932,NaN
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,...,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694,1.708192,-0.349998,-0.124676,1.076812,0.352214
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,...,7311.807185,-1.909479,4.379309,2014-06-01,0.027865,-0.534120,0.271423,0.135212,-1.155574,0.592137
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,...,8051.858683,4.631699,10.121321,2014-07-01,0.094101,0.714170,0.766707,0.456614,-3.949649,4.621536
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,...,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530,-1.851922,-0.751545,0.361647,-3.111151,-2.705239

## Model

In [10]:
import statsmodels.api as sm
import numpy as np
import pandas as pd

# 1. Define a list containing the names of the portfolio excess return columns.
portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

# 2. Create a dictionary to store the estimated betas for each portfolio (Conditional CCAPM).
portfolio_betas_conditional_ccapm = {}

# 3. Define the independent variables for the time-series regression as 'consumption_growth' and 'consumption_growth_x_cay'.
X_ts_conditional_ccapm = merged_df[['consumption_growth', 'consumption_growth_x_cay']].copy()

# 4. Add a constant term to the independent variables DataFrame.
X_ts_conditional_ccapm = sm.add_constant(X_ts_conditional_ccapm)

# 5. Iterate through each portfolio excess return column:
print("Performing time-series regressions for Conditional CCAPM (cay as multiplier)...")
for portfolio_col in portfolio_excess_return_cols:
    # a. Define the dependent variable as the current portfolio's excess return.
    y_ts_conditional_ccapm = merged_df[portfolio_col]

    # b. Drop rows with NaN values in the dependent variable and the corresponding rows in the independent variables DataFrame.
    valid_indices = y_ts_conditional_ccapm.dropna().index
    y_ts_cleaned_conditional_ccapm = y_ts_conditional_ccapm.loc[valid_indices]
    X_ts_cleaned_conditional_ccapm = X_ts_conditional_ccapm.loc[valid_indices]

    # Drop rows with NaN values in X_ts_cleaned_conditional_ccapm before fitting the model
    valid_X_indices = X_ts_cleaned_conditional_ccapm.dropna().index
    y_ts_cleaned_conditional_ccapm = y_ts_cleaned_conditional_ccapm.loc[valid_X_indices]
    X_ts_cleaned_conditional_ccapm = X_ts_cleaned_conditional_ccapm.loc[valid_X_indices]


    if not X_ts_cleaned_conditional_ccapm.empty and not y_ts_cleaned_conditional_ccapm.empty:
        # c. Fit an OLS model using sm.OLS with the cleaned dependent and independent variables.
        model_ts_conditional_ccapm = sm.OLS(y_ts_cleaned_conditional_ccapm, X_ts_cleaned_conditional_ccapm)
        results_ts_conditional_ccapm = model_ts_conditional_ccapm.fit()

        # d. Store the estimated coefficients in the dictionary.
        portfolio_betas_conditional_ccapm[portfolio_col] = {
            'beta_consumption': results_ts_conditional_ccapm.params['consumption_growth'],
            'beta_consumption_x_cay': results_ts_conditional_ccapm.params['consumption_growth_x_cay']
        }
    else:
         # Handle cases where there are no valid data points for regression
        portfolio_betas_conditional_ccapm[portfolio_col] = {
            'beta_consumption': np.nan,
            'beta_consumption_x_cay': np.nan
        }

# 6. Print the estimated betas for each portfolio.
print("Time-series regressions complete. Estimated Betas for Conditional CCAPM:")
for portfolio, betas in portfolio_betas_conditional_ccapm.items():
    print(f"{portfolio}:")
    print(f"  Beta Consumption: {betas['beta_consumption']:.4f}")
    print(f"  Beta Consumption x CAY: {betas['beta_consumption_x_cay']:.4f}")


# 7. Create a DataFrame of the estimated betas for cross-sectional regression and add a constant for lambda_0.
betas_df_conditional_ccapm = pd.DataFrame.from_dict(portfolio_betas_conditional_ccapm, orient='index')
betas_df_conditional_ccapm = sm.add_constant(betas_df_conditional_ccapm) # Add constant for lambda_0

# 8. Perform cross-sectional regressions
print("\nPerforming cross-sectional regressions for Conditional CCAPM...")
lambda_estimates_conditional_ccapm = []

for index, row in merged_df.iterrows():
    y_cs_conditional_ccapm = row[portfolio_excess_return_cols]

    # Drop NaN values from y_cs_conditional_ccapm and get the corresponding betas
    valid_portfolios = y_cs_conditional_ccapm.dropna().index
    y_cs_cleaned_conditional_ccapm = y_cs_conditional_ccapm.loc[valid_portfolios].astype(float)

    # Select the betas corresponding to the valid portfolios
    betas_for_cs_conditional_ccapm = betas_df_conditional_ccapm.loc[valid_portfolios].astype(float)

    # Ensure there are enough valid data points and betas for regression (at least 3 for intercept and two betas)
    if len(valid_portfolios) >= 3 and not betas_for_cs_conditional_ccapm.empty:
        try:
            model_cs_conditional_ccapm = sm.OLS(y_cs_cleaned_conditional_ccapm, betas_for_cs_conditional_ccapm)
            results_cs_conditional_ccapm = model_cs_conditional_ccapm.fit()
            # Ensure the number of parameters is 3 before appending (lambda_0, lambda_consumption, lambda_consumption_x_cay)
            if len(results_cs_conditional_ccapm.params) == 3:
                lambda_estimates_conditional_ccapm.append(results_cs_conditional_ccapm.params.tolist())
            else:
                 # Append NaNs if the number of parameters is not as expected
                lambda_estimates_conditional_ccapm.append([np.nan, np.nan, np.nan])
        except Exception as e:
            # Handle potential errors during regression
            print(f"Regression error at index {index}: {e}")
            lambda_estimates_conditional_ccapm.append([np.nan, np.nan, np.nan])
    else:
        # Append NaNs if regression cannot be performed
        lambda_estimates_conditional_ccapm.append([np.nan, np.nan, np.nan])

lambda_df_conditional_ccapm = pd.DataFrame(lambda_estimates_conditional_ccapm, columns=['lambda_0', 'lambda_consumption', 'lambda_consumption_x_cay'])
print("Cross-sectional regressions complete.")
#display(lambda_df_conditional_ccapm.head()) # Optional: display head of lambda_df_conditional_ccapm


# 9. Compute Fama–MacBeth lambdas and standard errors
print("\nComputing Fama-MacBeth lambdas and standard errors for Conditional CCAPM...")
lambda_0_mean_conditional_ccapm = lambda_df_conditional_ccapm['lambda_0'].mean()
lambda_0_sem_conditional_ccapm = lambda_df_conditional_ccapm['lambda_0'].sem()
lambda_consumption_mean_conditional_ccapm = lambda_df_conditional_ccapm['lambda_consumption'].mean()
lambda_consumption_sem_conditional_ccapm = lambda_df_conditional_ccapm['lambda_consumption'].sem()
lambda_consumption_x_cay_mean_conditional_ccapm = lambda_df_conditional_ccapm['lambda_consumption_x_cay'].mean()
lambda_consumption_x_cay_sem_conditional_ccapm = lambda_df_conditional_ccapm['lambda_consumption_x_cay'].sem()


print("Fama-MacBeth Lambda Estimates (Conditional CCAPM):")
print(f"Mean of lambda_0: {lambda_0_mean_conditional_ccapm:.4f}")
print(f"Standard Error of lambda_0: {lambda_0_sem_conditional_ccapm:.4f}")
print(f"Mean of lambda_consumption: {lambda_consumption_mean_conditional_ccapm:.4f}")
print(f"Standard Error of lambda_consumption: {lambda_consumption_sem_conditional_ccapm:.4f}")
print(f"Mean of lambda_consumption_x_cay: {lambda_consumption_x_cay_mean_conditional_ccapm:.4f}")
print(f"Standard Error of lambda_consumption_x_cay: {lambda_consumption_x_cay_sem_conditional_ccapm:.4f}")


# 10. Apply Shanken correction
print("\nApplying Shanken correction...")
# 1. Calculate the mean vector and covariance matrix of the factors
# Factors are consumption growth and consumption growth x cay interaction
factors_conditional_ccapm_shanken = merged_df[['consumption_growth', 'consumption_growth_x_cay']].dropna()
mu_f_conditional_ccapm = factors_conditional_ccapm_shanken.mean().values
Sigma_f_conditional_ccapm = factors_conditional_ccapm_shanken.cov().values

# 2. Calculate the Shanken correction factor
# Formula: (1 + mu_f' * inv(Sigma_f) * mu_f)
try:
    Sigma_f_inv_conditional_ccapm = np.linalg.inv(Sigma_f_conditional_ccapm)
    shanken_correction_factor_conditional_ccapm = (1 + mu_f_conditional_ccapm.T @ Sigma_f_inv_conditional_ccapm @ mu_f_conditional_ccapm)
except np.linalg.LinAlgError:
    print("Could not compute inverse of the covariance matrix. Skipping Shanken correction.")
    shanken_correction_factor_conditional_ccapm = np.nan


if not np.isnan(shanken_correction_factor_conditional_ccapm):
    # 3. Multiply the squared standard errors of the Fama-MacBeth lambdas by the Shanken correction factor
    lambda_0_shanken_variance_conditional_ccapm = (lambda_0_sem_conditional_ccapm**2) * shanken_correction_factor_conditional_ccapm
    lambda_consumption_shanken_variance_conditional_ccapm = (lambda_consumption_sem_conditional_ccapm**2) * shanken_correction_factor_conditional_ccapm
    lambda_consumption_x_cay_shanken_variance_conditional_ccapm = (lambda_consumption_x_cay_sem_conditional_ccapm**2) * shanken_correction_factor_conditional_ccapm


    # 4. Take the square root of the Shanken-corrected variances to get the Shanken-corrected standard errors
    lambda_0_shanken_sem_conditional_ccapm = np.sqrt(lambda_0_shanken_variance_conditional_ccapm)
    lambda_consumption_shanken_sem_conditional_ccapm = np.sqrt(lambda_consumption_shanken_variance_conditional_ccapm)
    lambda_consumption_x_cay_shanken_sem_conditional_ccapm = np.sqrt(lambda_consumption_x_cay_shanken_variance_conditional_ccapm)


    # 5. Calculate the t-statistics using the mean lambdas and Shanken-corrected standard errors
    lambda_0_shanken_tstat_conditional_ccapm = lambda_0_mean_conditional_ccapm / lambda_0_shanken_sem_conditional_ccapm
    lambda_consumption_shanken_tstat_conditional_ccapm = lambda_consumption_mean_conditional_ccapm / lambda_consumption_shanken_sem_conditional_ccapm
    lambda_consumption_x_cay_shanken_tstat_conditional_ccapm = lambda_consumption_x_cay_mean_conditional_ccapm / lambda_consumption_x_cay_shanken_sem_conditional_ccapm


    # 6. Print the Shanken-corrected standard errors and t-statistics
    print("\nShanken-corrected Results (Conditional CCAPM):")
    print(f"Shanken-corrected Standard Error of lambda_0: {lambda_0_shanken_sem_conditional_ccapm:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_0: {lambda_0_shanken_tstat_conditional_ccapm:.4f}")
    print(f"Shanken-corrected Standard Error of lambda_consumption: {lambda_consumption_shanken_sem_conditional_ccapm:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_consumption: {lambda_consumption_shanken_tstat_conditional_ccapm:.4f}")
    print(f"Shanken-corrected Standard Error of lambda_consumption_x_cay: {lambda_consumption_x_cay_shanken_sem_conditional_ccapm:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_consumption_x_cay: {lambda_consumption_x_cay_shanken_tstat_conditional_ccapm:.4f}")

else:
    print("\nShanken correction could not be applied.")


# 11. Compute cross-sectional R²
print("\nComputing average cross-sectional R-squared...")
cs_r_squared_values_conditional_ccapm = []

for index, row in merged_df.iterrows():
    y_cs_conditional_ccapm = row[portfolio_excess_return_cols]

    # Drop NaN values from y_cs_conditional_ccapm and get the corresponding betas
    valid_portfolios = y_cs_conditional_ccapm.dropna().index
    y_cs_cleaned_conditional_ccapm = y_cs_conditional_ccapm.loc[valid_portfolios].astype(float)

    # Select the betas corresponding to the valid portfolios
    betas_for_cs_conditional_ccapm = betas_df_conditional_ccapm.loc[valid_portfolios].astype(float)

    # Ensure there are enough valid data points and betas for regression (at least 3 for intercept and two betas)
    if len(valid_portfolios) >= 3 and not betas_for_cs_conditional_ccapm.empty:
        try:
            model_cs_conditional_ccapm = sm.OLS(y_cs_cleaned_conditional_ccapm, betas_for_cs_conditional_ccapm)
            results_cs_conditional_ccapm = model_cs_conditional_ccapm.fit()
            if len(results_cs_conditional_ccapm.params) == 3:
                 # Calculate R-squared for the cross-sectional regression
                y_cs_mean = y_cs_cleaned_conditional_ccapm.mean()
                ss_total = ((y_cs_cleaned_conditional_ccapm - y_cs_mean) ** 2).sum()
                # Calculate predicted values using the cross-sectional regression results
                predicted_y_cs = results_cs_conditional_ccapm.predict(betas_for_cs_conditional_ccapm)
                ss_residual = ((y_cs_cleaned_conditional_ccapm - predicted_y_cs) ** 2).sum()
                # Avoid division by zero if ss_total is zero
                if ss_total > 0:
                    cs_r_squared = 1 - (ss_residual / ss_total)
                    cs_r_squared_values_conditional_ccapm.append(cs_r_squared)
                else:
                    cs_r_squared_values_conditional_ccapm.append(np.nan) # Append NaN if ss_total is zero
            else:
                cs_r_squared_values_conditional_ccapm.append(np.nan)
        except Exception as e:
            print(f"Regression error at index {index}: {e}")
            cs_r_squared_values_conditional_ccapm.append(np.nan)
    else:
        cs_r_squared_values_conditional_ccapm.append(np.nan)


average_cs_r_squared_conditional_ccapm = np.nanmean(cs_r_squared_values_conditional_ccapm)

print(f"Average Cross-Sectional R-squared (Conditional CCAPM): {average_cs_r_squared_conditional_ccapm:.4f}")


# 12. Report results (Summary)
print("\n--- Conditional CCAPM Model Results (cay as multiplier) ---")
print(f"Mean lambda_consumption: {lambda_consumption_mean_conditional_ccapm:.4f}")
if not np.isnan(shanken_correction_factor_conditional_ccapm):
    print(f"Shanken-corrected t-statistic for lambda_consumption: {lambda_consumption_shanken_tstat_conditional_ccapm:.4f}")
else:
     print("Shanken-corrected t-statistic for lambda_consumption: N/A (Shanken correction not applied)")

print(f"Mean lambda_consumption_x_cay: {lambda_consumption_x_cay_mean_conditional_ccapm:.4f}")
if not np.isnan(shanken_correction_factor_conditional_ccapm):
    print(f"Shanken-corrected t-statistic for lambda_consumption_x_cay: {lambda_consumption_x_cay_shanken_tstat_conditional_ccapm:.4f}")
else:
    print("Shanken-corrected t-statistic for lambda_consumption_x_cay: N/A (Shanken correction not applied)")

print(f"Mean lambda_0: {lambda_0_mean_conditional_ccapm:.4f}")
if not np.isnan(shanken_correction_factor_conditional_ccapm):
    print(f"Shanken-corrected t-statistic for lambda_0: {lambda_0_shanken_tstat_conditional_ccapm:.4f}")
else:
    print("Shanken-corrected t-statistic for lambda_0: N/A (Shanken correction not applied)")

print(f"Average cross-sectional R-squared: {average_cs_r_squared_conditional_ccapm:.4f}")

print("\n--- Conditional CCAPM Summary ---")
print("Key Findings:")
print(f"* The estimated betas for the six portfolios show varying sensitivities to consumption growth and conditional consumption growth (consumption growth x cay).")
print(f"* The mean estimated consumption risk premium (lambda_consumption) is {lambda_consumption_mean_conditional_ccapm:.4f}.")
print(f"* The mean estimated conditional consumption risk premium (lambda_consumption_x_cay) is {lambda_consumption_x_cay_mean_conditional_ccapm:.4f}.")
print(f"* The mean estimated zero-beta rate (lambda_0) is {lambda_0_mean_conditional_ccapm:.4f}.")

if not np.isnan(shanken_correction_factor_conditional_ccapm):
    print("* Shanken-corrected t-statistics indicate the statistical significance of the estimated risk premia.")
    print(f"  - Consumption Risk Premium t-statistic: {lambda_consumption_shanken_tstat_conditional_ccapm:.4f}")
    print(f"  - Conditional Consumption Risk Premium t-statistic: {lambda_consumption_x_cay_shanken_tstat_conditional_ccapm:.4f}")
    print(f"  - Zero-Beta Rate t-statistic: {lambda_0_shanken_tstat_conditional_ccapm:.4f}")
else:
    print("* Shanken correction could not be applied due to issues with the covariance matrix.")

print(f"* The average cross-sectional R-squared of {average_cs_r_squared_conditional_ccapm:.4f} suggests the proportion of the cross-sectional variation in portfolio excess returns explained by the model.")

print("\nNext Steps:")
print("- Summarize all conditional model results and compare them to the unconditional models.")

Performing time-series regressions for Conditional CCAPM (cay as multiplier)...
Time-series regressions complete. Estimated Betas for Conditional CCAPM:
BV_excess_return:
  Beta Consumption: 0.0569
  Beta Consumption x CAY: 0.0774
BN_excess_return:
  Beta Consumption: 0.0927
  Beta Consumption x CAY: 0.0885
BG_excess_return:
  Beta Consumption: 0.0747
  Beta Consumption x CAY: 0.0471
SV_excess_return:
  Beta Consumption: 0.1501
  Beta Consumption x CAY: 0.1144
SN_excess_return:
  Beta Consumption: 0.1142
  Beta Consumption x CAY: 0.0838
SG_excess_return:
  Beta Consumption: 0.1164
  Beta Consumption x CAY: 0.0785

Performing cross-sectional regressions for Conditional CCAPM...
Cross-sectional regressions complete.

Computing Fama-MacBeth lambdas and standard errors for Conditional CCAPM...
Fama-MacBeth Lambda Estimates (Conditional CCAPM):
Mean of lambda_0: -5.6277
Standard Error of lambda_0: 0.5381
Mean of lambda_consumption: 0.2559
Standard Error of lambda_consumption: 9.8020
Mean of lambda_consumption_x_cay: 15.4455
Standard Error of lambda_consumption_x_cay: 12.9501

Applying Shanken correction...

Shanken-corrected Results (Conditional CCAPM):
Shanken-corrected Standard Error of lambda_0: 0.5552
Shanken-corrected t-statistic for lambda_0: -10.1358
Shanken-corrected Standard Error of lambda_consumption: 10.1135
Shanken-corrected t-statistic for lambda_consumption: 0.0253
Shanken-corrected Standard Error of lambda_consumption_x_cay: 13.3616
Shanken-corrected t-statistic for lambda_consumption_x_cay: 1.1560

Computing average cross-sectional R-squared...
Average Cross-Sectional R-squared (Conditional CCAPM): 0.6715

--- Conditional CCAPM Model Results (cay as multiplier) ---
Mean lambda_consumption: 0.2559
Shanken-corrected t-statistic for lambda_consumption: 0.0253
Mean lambda_consumption_x_cay: 15.4455
Shanken-corrected t-statistic for lambda_consumption_x_cay: 1.1560
Mean lambda_0: -5.6277
Shanken-corrected t-statistic for lambda_0: -10.1358
Average cross-sectional R-squared: 0.6715

--- Conditional CCAPM Summary ---
Key Findings:
* The estimated betas for the six portfolios show varying sensitivities to consumption growth and conditional consumption growth (consumption growth x cay).
* The mean estimated consumption risk premium (lambda_consumption) is 0.2559.
* The mean estimated conditional consumption risk premium (lambda_consumption_x_cay) is 15.4455.
* The mean estimated zero-beta rate (lambda_0) is -5.6277.
* Shanken-corrected t-statistics indicate the statistical significance of the estimated risk premia.
  - Consumption Risk Premium t-statistic: 0.0253
  - Conditional Consumption Risk Premium t-statistic: 1.1560
  - Zero-Beta Rate t-statistic: -10.1358
* The average cross-sectional R-squared of 0.6715 suggests the proportion of the cross-sectional variation in portfolio excess returns explained by the model.

Next Steps:
- Summarize all conditional model results and compare them to the unconditional models.

## Pricing Error

In [13]:
# 1. Calculate Average Actual Excess Return for each portfolio
average_actual_excess_returns = merged_df[portfolio_excess_return_cols].mean()

# 2. Calculate Predicted Expected Return for each portfolio (using average lambdas and first-stage betas)
predicted_expected_returns = pd.Series(index=portfolio_excess_return_cols)

# portfolio_betas_conditional_ccapm already contains the betas with index as portfolio names.
# Need to drop the 'const' column to get just the factor betas.
portfolio_betas_only = betas_df_conditional_ccapm.drop(columns=['const']) # This df contains beta_consumption and beta_consumption_x_cay

lambda_0 = lambda_0_mean_conditional_ccapm
lambda_consumption = lambda_consumption_mean_conditional_ccapm
lambda_consumption_x_cay = lambda_consumption_x_cay_mean_conditional_ccapm

for portfolio_col in portfolio_excess_return_cols:
    beta_c = portfolio_betas_only.loc[portfolio_col, 'beta_consumption']
    beta_cx_cay = portfolio_betas_only.loc[portfolio_col, 'beta_consumption_x_cay']
    predicted_expected_returns[portfolio_col] = (lambda_0 +
                                                 lambda_consumption * beta_c +
                                                 lambda_consumption_x_cay * beta_cx_cay)

# 3. Calculate Average Pricing Errors (Alphas) for each portfolio
average_pricing_errors = average_actual_excess_returns - predicted_expected_returns

print("\nAverage Pricing Errors (Alphas) for each portfolio (Revised):")
print(average_pricing_errors)

# 4. Calculate the time-series of second-stage residuals (u_i,t) for J-statistic
residuals_cs = pd.DataFrame(index=merged_df.index, columns=portfolio_excess_return_cols)

# Ensure lambda_df_conditional_ccapm and merged_df have aligned indices/dates
# Both should have 132 rows. merged_df has 132 rows. lambda_df_conditional_ccapm has 132 rows.
# We need to iterate through each time step (row) of merged_df and lambda_df_conditional_ccapm

for t_idx in range(len(merged_df)):
    # Get the time-varying lambdas for the current time step
    current_lambdas = lambda_df_conditional_ccapm.iloc[t_idx]
    lambda_0_t = current_lambdas['lambda_0']
    lambda_consumption_t = current_lambdas['lambda_consumption']
    lambda_consumption_x_cay_t = current_lambdas['lambda_consumption_x_cay']

    for portfolio_col in portfolio_excess_return_cols:
        R_i_t = merged_df[portfolio_col].iloc[t_idx] # Actual excess return at time t for portfolio i

        # Get betas for the current portfolio (these are constant across time)
        beta_c = portfolio_betas_only.loc[portfolio_col, 'beta_consumption']
        beta_cx_cay = portfolio_betas_only.loc[portfolio_col, 'beta_consumption_x_cay']

        # Calculate predicted return at time t for portfolio i using time-varying lambdas and fixed betas
        predicted_R_i_t = (lambda_0_t +
                           lambda_consumption_t * beta_c +
                           lambda_consumption_x_cay_t * beta_cx_cay)

        # Calculate the residual for this portfolio at this time step
        residuals_cs.loc[merged_df.index[t_idx], portfolio_col] = R_i_t - predicted_R_i_t

# Clean residuals by dropping NaNs (e.g., from BV_excess_return where actual returns were NaN)
residuals_cs_cleaned = residuals_cs.dropna()

# 5. Calculate the covariance matrix of these second-stage residuals
Sigma_u = residuals_cs_cleaned.cov()

# 6. Calculate the Chi-Square (J-statistic)
# Number of portfolios (assets)
N = len(portfolio_excess_return_cols)

# Number of factors (including constant) for the chi-square test
# lambda_0, lambda_consumption, lambda_consumption_x_cay
K = 3

# Degrees of freedom
df = N - K

# Number of time observations for which residuals were calculated
T_cleaned = len(residuals_cs_cleaned)

if df <= 0:
    print("Degrees of freedom for Chi-square is non-positive. Cannot compute Chi-square statistic.")
    chi_square_value = np.nan
else:
    try:
        # Convert average_pricing_errors (alphas) to a column vector
        # Ensure it only contains relevant portfolios and is aligned with the residuals_cs_cleaned columns
        average_pricing_errors_vector = average_pricing_errors[residuals_cs_cleaned.columns].values.reshape(-1, 1)

        # Use pseudo-inverse for robustness against singular matrices
        Sigma_u_inv = np.linalg.pinv(Sigma_u)

        # Chi-square statistic (J-statistic)
        # J = T * alpha_bar' * inv(Sigma_u) * alpha_bar
        chi_square_value = T_cleaned * (average_pricing_errors_vector.T @ Sigma_u_inv @ average_pricing_errors_vector)
        chi_square_value = chi_square_value[0, 0] # Extract scalar value from the 1x1 array

        print(f"\nChi-Square (J-statistic) for Conditional CCAPM (Revised): {chi_square_value:.4f}")
        print(f"Degrees of Freedom: {df}")
    except np.linalg.LinAlgError:
        print("\nCould not compute inverse of the covariance matrix of residuals. Skipping Chi-Square calculation.")
        chi_square_value = np.nan

print("\n--- Pricing Error Summary (Revised) ---")
print("Average pricing errors (Alphas):")
for portfolio, alpha in average_pricing_errors.items():
    print(f"  {portfolio}: {alpha:.4f}")

if not np.isnan(chi_square_value):
    print(f"Chi-Square (J-statistic): {chi_square_value:.4f}")
    print(f"Degrees of Freedom: {df}")
else:
    print("Chi-Square (J-statistic): N/A (could not be computed)")

Average Pricing Errors (Alphas) for each portfolio (Revised):
BV_excess_return    0.934394
BN_excess_return   -0.207356
BG_excess_return   -0.013551
SV_excess_return   -0.015785
SN_excess_return    0.429336
SG_excess_return   -0.259632
dtype: float64

Chi-Square (J-statistic) for Conditional CCAPM (Revised): 11.8557
Degrees of Freedom: 3

--- Pricing Error Summary (Revised) ---
Average pricing errors (Alphas):
  BV_excess_return: 0.9344
  BN_excess_return: -0.2074
  BG_excess_return: -0.0136
  SV_excess_return: -0.0158
  SN_excess_return: 0.4293
  SG_excess_return: -0.2596
Chi-Square (J-statistic): 11.8557
Degrees of Freedom: 3