## Data Processing

In [1]:
import pandas as pd

df_ff6 = pd.read_csv('/content/FF6.csv')
df_cay = pd.read_csv('/content/cay_index.csv')
df_market = pd.read_csv('/content/Market-Returns-Cleaned.csv')
df_consumption = pd.read_csv('/content/Consumption-Cleaned.csv')
df_ff6_factors = pd.read_csv('/content/FF6_Factors.csv')
df_income = pd.read_csv('/content/Income-Cleaned.csv')
df_risk_free = pd.read_csv('/content/Risk-Free-Cleaned.csv')

print("FF6.csv:")
display(df_ff6.head())
df_ff6.info()

print("\ncay_index.csv:")
display(df_cay.head())
df_cay.info()

print("\nMarket-Returns-Cleaned.csv:")
display(df_market.head())
df_market.info()

print("\nConsumption-Cleaned.csv:")
display(df_consumption.head())
df_consumption.info()

print("\nFF6_Factors.csv:")
display(df_ff6_factors.head())
df_ff6_factors.info()

print("\nIncome-Cleaned.csv:")
display(df_income.head())
df_income.info()

print("\nRisk-Free-Cleaned.csv:")
display(df_risk_free.head())
df_risk_free.info()

FF6.csv:

,month,Portfolios BV returns (%),Portfolios BN returns (%),Portfolios BG returns (%),Portfolios SV returns (%),Portfolios SN returns (%),Portfolios SG returns (%)
0,Apr-14,NaN,0.262471,0.172784,13.215249,6.550439,5.111012
1,May-14,NaN,23.102455,7.275463,27.552673,24.288677,15.810411
2,Jun-14,NaN,1.873951,7.745938,18.652457,16.839867,13.023586
3,Jul-14,NaN,-3.014671,1.413907,-7.500655,-2.044578,2.165995
4,Aug-14,NaN,-2.396891,4.203748,-0.729519,4.765247,4.484203

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      132 non-null    object
 1   Portfolios BV returns (%)  115 non-null    float64
 2   Portfolios BN returns (%)  132 non-null    float64
 3   Portfolios BG returns (%)  132 non-null    float64
 4   Portfolios SV returns (%)  132 non-null    float64
 5   Portfolios SN returns (%)  132 non-null    float64
 6   Portfolios SG returns (%)  132 non-null    float64
dtypes: float64(6), object(1)
memory usage: 7.3+ KB

cay_index.csv:

   month_x       cay
0  2014-04  0.057466
1  2014-05 -0.025694
2  2014-06  0.027865
3  2014-07  0.094101
4  2014-08  0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   month_x  132 non-null    object
 1   cay      132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Market-Returns-Cleaned.csv:

,month,market_return,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122
0,Apr-14,-0.006342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,May-14,0.008682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jun-14,0.015540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jul-14,-0.004266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aug-14,0.001078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Columns: 123 entries, month  to Unnamed: 122
dtypes: float64(122), object(1)
memory usage: 127.0+ KB

Consumption-Cleaned.csv:

     month  weighted_avg_consumption
0  2014-04               7208.683747
1  2014-05               7005.035044
2  2014-06               7311.807185
3  2014-07               8051.858683
4  2014-08               7449.553517

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   month                     132 non-null    object
 1   weighted_avg_consumption  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

FF6_Factors.csv:

      Date       SMB        HML       WML        MF        RF
0  2014-04  5.592209   7.810347 -3.415147  0.013121  0.701553
1  2014-05  4.340620  10.499133 -8.697000  9.950842  0.693805
2  2014-06  9.644133   5.182859  2.562922  6.929204  0.699993
3  2014-07  0.896284  -9.319494 -1.127898 -0.233564  0.700633
4  2014-08  3.732569  -4.896134  5.494075  2.452235  0.637590

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    132 non-null    object
 1   SMB     132 non-null    float64
 2   HML     132 non-null    float64
 3   WML     132 non-null    float64
 4   MF      132 non-null    float64
 5   RF      132 non-null    float64
dtypes: float64(5), object(1)
memory usage: 6.3+ KB

Income-Cleaned.csv:

     month  national_weighted_avg_income
0  2014-04                   12811.15146
1  2014-05                   14071.83162
2  2014-06                   13803.13302
3  2014-07                   14442.45259
4  2014-08                   13169.36297

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   month                         132 non-null    object
 1   national_weighted_avg_income  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Risk-Free-Cleaned.csv:

     month   Yeild
0  2014-04  8.8550
1  2014-05  8.6456
2  2014-06  8.5619
3  2014-07  8.6456
4  2014-08  8.6038

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   132 non-null    object
 1   Yeild   132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

In [4]:
df_ff6['month'] = pd.to_datetime(df_ff6['month'], format='%b-%y')
df_ff6_factors['Date'] = pd.to_datetime(df_ff6_factors['Date'])
df_market['month '] = pd.to_datetime(df_market['month '], format='%b-%y')
df_risk_free['month'] = pd.to_datetime(df_risk_free['month'])
df_cay['month_x'] = pd.to_datetime(df_cay['month_x'])
df_consumption['month'] = pd.to_datetime(df_consumption['month'])
df_income['month'] = pd.to_datetime(df_income['month'])

# Rename date columns for consistency before merging
df_ff6.rename(columns={'month': 'date'}, inplace=True)
df_risk_free.rename(columns={'month': 'date'}, inplace=True)
df_ff6_factors.rename(columns={'Date': 'date'}, inplace=True)
df_market.rename(columns={'month ': 'date'}, inplace=True)
df_cay.rename(columns={'month_x': 'date'}, inplace=True)
df_consumption.rename(columns={'month': 'date'}, inplace=True)
df_income.rename(columns={'month': 'date'}, inplace=True)


merged_df = pd.merge(df_ff6, df_risk_free, on='date', how='inner')
merged_df = pd.merge(merged_df, df_ff6_factors, on='date', how='inner')
merged_df = pd.merge(merged_df, df_market[['date', 'market_return']], on='date', how='inner')

portfolio_cols = ['Portfolios BV returns (%)', 'Portfolios BN returns (%)', 'Portfolios BG returns (%)', 'Portfolios SV returns (%)', 'Portfolios SN returns (%)', 'Portfolios SG returns (%)']
for col in portfolio_cols:
    merged_df[f'{col}_excess'] = merged_df[col] - merged_df['Yeild']

merged_df['market_return_excess'] = merged_df['market_return'] - merged_df['Yeild']

merged_df.rename(columns={
                          'Portfolios BV returns (%)_excess': 'BV_excess_return',
                          'Portfolios BN returns (%)_excess': 'BN_excess_return',
                          'Portfolios BG returns (%)_excess': 'BG_excess_return',
                          'Portfolios SV returns (%)_excess': 'SV_excess_return',
                          'Portfolios SN returns (%)_excess': 'SN_excess_return',
                          'Portfolios SG returns (%)_excess': 'SG_excess_return',
                          'market_return_excess': 'market_excess_return',
                          'SMB': 'smb', 'HML': 'hml', 'WML': 'wml', 'MF': 'mf', 'RF': 'rf',
                          'weighted_avg_consumption': 'consumption',
                          'national_weighted_avg_income': 'income',
                          'cay': 'cay_index'}, inplace=True)


columns_to_drop = portfolio_cols + ['market_return', 'Yeild']
merged_df.drop(columns=columns_to_drop, inplace=True)

display(merged_df.head())
merged_df.info()

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  132 non-null    datetime64[ns]
 1   smb                   132 non-null    float64
 2   hml                   132 non-null    float64
 3   wml                   132 non-null    float64
 4   mf                    132 non-null    float64
 5   rf                    132 non-null    float64
 6   BV_excess_return      115 non-null    float64
 7   BN_excess_return      132 non-null    float64
 8   BG_excess_return      132 non-null    float64
 9   SV_excess_return      132 non-null    float64
 10  SN_excess_return      132 non-null    float64
 11  SG_excess_return      132 non-null    float64
 12  market_excess_return  132 non-null    float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 13.5 KB

In [5]:
df_income.rename(columns={'month': 'date'}, inplace=True)
df_consumption.rename(columns={'month': 'date'}, inplace=True)

merged_df = merged_df.loc[:,~merged_df.columns.duplicated()]

merged_df = pd.merge(merged_df, df_income, on='date', how='inner')
merged_df = pd.merge(merged_df, df_consumption, on='date', how='inner')

print(merged_df.columns)

merged_df['income_growth'] = merged_df['national_weighted_avg_income'].pct_change() * 100
merged_df['consumption_growth'] = merged_df['weighted_avg_consumption'].pct_change() * 100

display(merged_df.head())

Index(['date', 'smb', 'hml', 'wml', 'mf', 'rf', 'BV_excess_return',
       'BN_excess_return', 'BG_excess_return', 'SV_excess_return',
       'SN_excess_return', 'SG_excess_return', 'market_excess_return',
       'national_weighted_avg_income', 'weighted_avg_consumption'],
      dtype='object')

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325

In [7]:
merged_df = pd.merge(merged_df, df_cay, left_on='date', right_on='date', how='inner')

display(merged_df.head())
merged_df.info()

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,cay
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN,0.057466
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047,-0.025694
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309,0.027865
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321,0.094101
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325,0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          132 non-null    datetime64[ns]
 1   smb                           132 non-null    float64
 2   hml                           132 non-null    float64
 3   wml                           132 non-null    float64
 4   mf                            132 non-null    float64
 5   rf                            132 non-null    float64
 6   BV_excess_return              115 non-null    float64
 7   BN_excess_return              132 non-null    float64
 8   BG_excess_return              132 non-null    float64
 9   SV_excess_return              132 non-null    float64
 10  SN_excess_return              132 non-null    float64
 11  SG_excess_return              132 non-null    float64
 12  market_excess_return          132 non-null    float64
 13  national_weighted_avg_income  132 non-null    float64
 14  weighted_avg_consumption      132 non-null    float64
 15  income_growth                 131 non-null    float64
 16  consumption_growth            131 non-null    float64
 17  cay                           132 non-null    float64
dtypes: datetime64[ns](1), float64(17)
memory usage: 18.7 KB

In [8]:
macro_vars = ['income_growth', 'consumption_growth', 'cay']

for var in macro_vars:
    mean = merged_df[var].mean()
    std = merged_df[var].std()
    merged_df[f'{var}_standardized'] = (merged_df[var] - mean) / std

display(merged_df.head())

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,...,SG_excess_return,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,cay,income_growth_standardized,consumption_growth_standardized,cay_standardized
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,...,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN,0.057466,NaN,NaN,0.278844
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,...,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047,-0.025694,1.708192,-0.349998,-0.124676
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,...,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309,0.027865,-0.534120,0.271423,0.135212
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,...,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321,0.094101,0.714170,0.766707,0.456614
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,...,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325,0.074530,-1.851922,-0.751545,0.361647

In [9]:
merged_df['market_excess_return_x_cay'] = merged_df['market_excess_return'] * merged_df['cay_standardized']
#merged_df['human_capital_return_x_cay'] = merged_df['human_capital_return'] * merged_df['cay_standardized']
merged_df['consumption_growth_x_cay'] = merged_df['consumption_growth'] * merged_df['cay_standardized']

display(merged_df.head())

,date,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,...,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,cay,income_growth_standardized,consumption_growth_standardized,cay_standardized,market_excess_return_x_cay,consumption_growth_x_cay
0,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,...,12811.15146,7208.683747,NaN,NaN,0.057466,NaN,NaN,0.278844,-2.470932,NaN
1,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,...,14071.83162,7005.035044,9.840491,-2.825047,-0.025694,1.708192,-0.349998,-0.124676,1.076812,0.352214
2,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,...,13803.13302,7311.807185,-1.909479,4.379309,0.027865,-0.534120,0.271423,0.135212,-1.155574,0.592137
3,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,...,14442.45259,8051.858683,4.631699,10.121321,0.094101,0.714170,0.766707,0.456614,-3.949649,4.621536
4,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,...,13169.36297,7449.553517,-8.814913,-7.480325,0.074530,-1.851922,-0.751545,0.361647,-3.111151,-2.705239

## Model

In [13]:
import statsmodels.api as sm
import numpy as np
import pandas as pd
from scipy.stats import f

# 1. Define a list containing the names of the portfolio excess return columns.
portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

# Find common valid indices across all portfolios for a balanced panel
common_valid_indices = merged_df[portfolio_excess_return_cols[0]].dropna().index
for col in portfolio_excess_return_cols[1:]:
    common_valid_indices = common_valid_indices.intersection(merged_df[col].dropna().index)

# Convert to list for consistent indexing
common_valid_indices = common_valid_indices.tolist()
T = len(common_valid_indices) # Number of time periods for GRS and balanced panel regressions
N = len(portfolio_excess_return_cols) # Number of portfolios

# 2. Create dictionaries to store the estimated betas, alphas, and residuals for each portfolio (Conditional CAPM).
portfolio_betas_conditional_capm = {}
portfolio_alphas_ts = {}
portfolio_residuals_ts = {}

# 3. Define the independent variables for the time-series regression as the 'market_excess_return' and 'market_excess_return_x_cay' columns.
X_ts_conditional_capm = merged_df[['market_excess_return', 'market_excess_return_x_cay']].loc[common_valid_indices].copy()

# 4. Add a constant term to the independent variables DataFrame.
X_ts_conditional_capm = sm.add_constant(X_ts_conditional_capm)

# 5. Iterate through each portfolio excess return column:
print("Performing time-series regressions for Conditional CAPM (cay as multiplier) on a balanced panel...")
for portfolio_col in portfolio_excess_return_cols:
    # a. Define the dependent variable as the current portfolio's excess return for the common valid indices.
    y_ts_conditional_capm = merged_df.loc[common_valid_indices, portfolio_col]

    if not X_ts_conditional_capm.empty and not y_ts_conditional_capm.empty:
        # c. Fit an OLS model using sm.OLS.
        model_ts_conditional_capm = sm.OLS(y_ts_conditional_capm, X_ts_conditional_capm)
        results_ts_conditional_capm = model_ts_conditional_capm.fit()

        # d. Store the estimated coefficients, alpha, and residuals.
        portfolio_betas_conditional_capm[portfolio_col] = {
            'beta_market': results_ts_conditional_capm.params['market_excess_return'],
            'beta_market_x_cay': results_ts_conditional_capm.params['market_excess_return_x_cay']
        }
        portfolio_alphas_ts[portfolio_col] = results_ts_conditional_capm.params['const']
        portfolio_residuals_ts[portfolio_col] = results_ts_conditional_capm.resid
    else:
         # Handle cases where there are no valid data points for regression
        portfolio_betas_conditional_capm[portfolio_col] = {
            'beta_market': np.nan,
            'beta_market_x_cay': np.nan
        }
        portfolio_alphas_ts[portfolio_col] = np.nan
        portfolio_residuals_ts[portfolio_col] = pd.Series(dtype='float64') # Empty series


print("Time-series regressions complete. Estimated Betas for Conditional CAPM (balanced panel):")
for portfolio, betas in portfolio_betas_conditional_capm.items():
    print(f"{portfolio}:")
    print(f"  Beta Market: {betas['beta_market']:.4f}")
    print(f"  Beta Market x CAY: {betas['beta_market_x_cay']:.4f}")


# 7. Create a DataFrame of the estimated betas for cross-sectional regression and add a constant for lambda_0.
betas_df_conditional_capm = pd.DataFrame.from_dict(portfolio_betas_conditional_capm, orient='index')
betas_df_conditional_capm = sm.add_constant(betas_df_conditional_capm) # Add constant for lambda_0

# 8. Perform cross-sectional regressions
print("\nPerforming cross-sectional regressions for Conditional CAPM...")
lambda_estimates_conditional_capm = []

# Use only the common valid indices for y_cs
merged_df_cs = merged_df.loc[common_valid_indices].copy()

for index, row in merged_df_cs.iterrows():
    y_cs_conditional_capm = row[portfolio_excess_return_cols]

    # No need to drop NaNs here if common_valid_indices already handled it
    y_cs_cleaned_conditional_capm = y_cs_conditional_capm.astype(float)
    betas_for_cs_conditional_capm = betas_df_conditional_capm.astype(float)

    # Ensure there are enough valid data points and betas for regression (at least 3 for intercept and two betas)
    if len(y_cs_cleaned_conditional_capm) >= 3 and not betas_for_cs_conditional_capm.empty:
        try:
            model_cs_conditional_capm = sm.OLS(y_cs_cleaned_conditional_capm, betas_for_cs_conditional_capm)
            results_cs_conditional_capm = model_cs_conditional_capm.fit()
            # Ensure the number of parameters is 3 before appending (lambda_0, lambda_market, lambda_market_x_cay)
            if len(results_cs_conditional_capm.params) == 3:
                lambda_estimates_conditional_capm.append(results_cs_conditional_capm.params.tolist())
            else:
                 # Append NaNs if the number of parameters is not as expected
                lambda_estimates_conditional_capm.append([np.nan, np.nan, np.nan])
        except Exception as e:
            # Handle potential errors during regression
            print(f"Regression error at index {index}: {e}")
            lambda_estimates_conditional_capm.append([np.nan, np.nan, np.nan])
    else:
        # Append NaNs if regression cannot be performed
        lambda_estimates_conditional_capm.append([np.nan, np.nan, np.nan])

lambda_df_conditional_capm = pd.DataFrame(lambda_estimates_conditional_capm, columns=['lambda_0', 'lambda_market', 'lambda_market_x_cay'])
print("Cross-sectional regressions complete.")
#display(lambda_df_conditional_capm.head()) # Optional: display head of lambda_df_conditional_capm


# 9. Compute Fama–MacBeth lambdas and standard errors
print("\nComputing Fama-MacBeth lambdas and standard errors for Conditional CAPM...")
lambda_0_mean_conditional_capm = lambda_df_conditional_capm['lambda_0'].mean()
lambda_0_sem_conditional_capm = lambda_df_conditional_capm['lambda_0'].sem()
lambda_market_mean_conditional_capm = lambda_df_conditional_capm['lambda_market'].mean()
lambda_market_sem_conditional_capm = lambda_df_conditional_capm['lambda_market'].sem()
lambda_market_x_cay_mean_conditional_capm = lambda_df_conditional_capm['lambda_market_x_cay'].mean()
lambda_market_x_cay_sem_conditional_capm = lambda_df_conditional_capm['lambda_market_x_cay'].sem()


print("Fama-MacBeth Lambda Estimates (Conditional CAPM):")
print(f"Mean of lambda_0: {lambda_0_mean_conditional_capm:.4f}")
print(f"Standard Error of lambda_0: {lambda_0_sem_conditional_capm:.4f}")
print(f"Mean of lambda_market: {lambda_market_mean_conditional_capm:.4f}")
print(f"Standard Error of lambda_market: {lambda_market_sem_conditional_capm:.4f}")
print(f"Mean of lambda_market_x_cay: {lambda_market_x_cay_mean_conditional_capm:.4f}")
print(f"Standard Error of lambda_market_x_cay: {lambda_market_x_cay_sem_conditional_capm:.4f}")


# 10. Apply Shanken correction
print("\nApplying Shanken correction...")
# 1. Calculate the mean vector and covariance matrix of the factors
# Factors are market excess return and market excess return x cay interaction
# Ensure factors also use the common_valid_indices for consistency
factors_conditional_capm_shanken = merged_df[['market_excess_return', 'market_excess_return_x_cay']].loc[common_valid_indices].dropna()
mu_f_conditional_capm = factors_conditional_capm_shanken.mean().values
Sigma_f_conditional_capm = factors_conditional_capm_shanken.cov().values

# 2. Calculate the Shanken correction factor
# Formula: (1 + mu_f' * inv(Sigma_f) * mu_f)
try:
    Sigma_f_inv_conditional_capm = np.linalg.inv(Sigma_f_conditional_capm)
    shanken_correction_factor_conditional_capm = (1 + mu_f_conditional_capm.T @ Sigma_f_inv_conditional_capm @ mu_f_conditional_capm)
except np.linalg.LinAlgError:
    print("Could not compute inverse of the covariance matrix. Skipping Shanken correction.")
    shanken_correction_factor_conditional_capm = np.nan


if not np.isnan(shanken_correction_factor_conditional_capm):
    # 3. Multiply the squared standard errors of the Fama-MacBeth lambdas by the Shanken correction factor
    lambda_0_shanken_variance_conditional_capm = (lambda_0_sem_conditional_capm**2) * shanken_correction_factor_conditional_capm
    lambda_market_shanken_variance_conditional_capm = (lambda_market_sem_conditional_capm**2) * shanken_correction_factor_conditional_capm
    lambda_market_x_cay_shanken_variance_conditional_capm = (lambda_market_x_cay_sem_conditional_capm**2) * shanken_correction_factor_conditional_capm


    # 4. Take the square root of the Shanken-corrected variances to get the Shanken-corrected standard errors
    lambda_0_shanken_sem_conditional_capm = np.sqrt(lambda_0_shanken_variance_conditional_capm)
    lambda_market_shanken_sem_conditional_capm = np.sqrt(lambda_market_shanken_variance_conditional_capm)
    lambda_market_x_cay_shanken_sem_conditional_capm = np.sqrt(lambda_market_x_cay_shanken_variance_conditional_capm)


    # 5. Calculate the t-statistics using the mean lambdas and Shanken-corrected standard errors
    lambda_0_shanken_tstat_conditional_capm = lambda_0_mean_conditional_capm / lambda_0_shanken_sem_conditional_capm
    lambda_market_shanken_tstat_conditional_capm = lambda_market_mean_conditional_capm / lambda_market_shanken_sem_conditional_capm
    lambda_market_x_cay_shanken_tstat_conditional_capm = lambda_market_x_cay_mean_conditional_capm / lambda_market_x_cay_shanken_sem_conditional_capm


    # 6. Print the Shanken-corrected standard errors and t-statistics
    print("\nShanken-corrected Results (Conditional CAPM):")
    print(f"Shanken-corrected Standard Error of lambda_0: {lambda_0_shanken_sem_conditional_capm:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_0: {lambda_0_shanken_tstat_conditional_capm:.4f}")
    print(f"Shanken-corrected Standard Error of lambda_market: {lambda_market_shanken_sem_conditional_capm:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_market: {lambda_market_shanken_tstat_conditional_capm:.4f}")
    print(f"Shanken-corrected Standard Error of lambda_market_x_cay: {lambda_market_x_cay_shanken_sem_conditional_capm:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_market_x_cay: {lambda_market_x_cay_shanken_tstat_conditional_capm:.4f}")

else:
    print("\nShanken correction could not be applied.")


# 11. Compute cross-sectional R²
print("\nComputing average cross-sectional R-squared...")
cs_r_squared_values_conditional_capm = []

for index, row in merged_df_cs.iterrows(): # Use merged_df_cs (balanced panel)
    y_cs_conditional_capm = row[portfolio_excess_return_cols]

    y_cs_cleaned_conditional_capm = y_cs_conditional_capm.astype(float)
    betas_for_cs_conditional_capm = betas_df_conditional_capm.astype(float)

    if len(y_cs_cleaned_conditional_capm) >= 3 and not betas_for_cs_conditional_capm.empty:
        try:
            model_cs_conditional_capm = sm.OLS(y_cs_cleaned_conditional_capm, betas_for_cs_conditional_capm)
            results_cs_conditional_capm = model_cs_conditional_capm.fit()
            if len(results_cs_conditional_capm.params) == 3:
                 # Calculate R-squared for the cross-sectional regression
                y_cs_mean = y_cs_cleaned_conditional_capm.mean()
                ss_total = ((y_cs_cleaned_conditional_capm - y_cs_mean) ** 2).sum()
                # Calculate predicted values using the cross-sectional regression results
                predicted_y_cs = results_cs_conditional_capm.predict(betas_for_cs_conditional_capm)
                ss_residual = ((y_cs_cleaned_conditional_capm - predicted_y_cs) ** 2).sum()
                # Avoid division by zero if ss_total is zero
                if ss_total > 0:
                    cs_r_squared = 1 - (ss_residual / ss_total)
                    cs_r_squared_values_conditional_capm.append(cs_r_squared)
                else:
                    cs_r_squared_values_conditional_capm.append(np.nan) # Append NaN if ss_total is zero
            else:
                cs_r_squared_values_conditional_capm.append(np.nan)
        except Exception as e:
            print(f"Regression error at index {index}: {e}")
            cs_r_squared_values_conditional_capm.append(np.nan)
    else:
        cs_r_squared_values_conditional_capm.append(np.nan)


average_cs_r_squared_conditional_capm = np.nanmean(cs_r_squared_values_conditional_capm)

print(f"Average Cross-Sectional R-squared (Conditional CAPM): {average_cs_r_squared_conditional_capm:.4f}")


# 12. Report results (Summary)
print("\n--- Conditional CAPM Model Results (cay as multiplier) ---")
print(f"Mean lambda_market: {lambda_market_mean_conditional_capm:.4f}")
if not np.isnan(shanken_correction_factor_conditional_capm):
    print(f"Shanken-corrected t-statistic for lambda_market: {lambda_market_shanken_tstat_conditional_capm:.4f}")
else:
     print("Shanken-corrected t-statistic for lambda_market: N/A (Shanken correction not applied)")

print(f"Mean lambda_market_x_cay: {lambda_market_x_cay_mean_conditional_capm:.4f}")
if not np.isnan(shanken_correction_factor_conditional_capm):
    print(f"Shanken-corrected t-statistic for lambda_market_x_cay: {lambda_market_x_cay_shanken_tstat_conditional_capm:.4f}")
else:
    print("Shanken-corrected t-statistic for lambda_market_x_cay: N/A (Shanken correction not applied)")

print(f"Mean lambda_0: {lambda_0_mean_conditional_capm:.4f}")
if not np.isnan(shanken_correction_factor_conditional_capm):
    print(f"Shanken-corrected t-statistic for lambda_0: {lambda_0_shanken_tstat_conditional_capm:.4f}")
else:
    print("Shanken-corrected t-statistic for lambda_0: N/A (Shanken correction not applied)")

print(f"Average cross-sectional R-squared: {average_cs_r_squared_conditional_capm:.4f}")


# --- New Calculations: Average Pricing Error and GRS F-statistic ---

# Calculate Average Pricing Errors
print("\n--- Average Pricing Errors (Conditional CAPM) ---")
average_pricing_errors = {}
for portfolio_col in portfolio_excess_return_cols:
    # Average actual excess return for this portfolio (over the balanced panel period)
    avg_actual_excess_return = merged_df.loc[common_valid_indices, portfolio_col].mean()

    # Get betas from the (now balanced) time-series regressions
    betas = portfolio_betas_conditional_capm[portfolio_col]

    # Calculate predicted average excess return using mean Fama-MacBeth lambdas
    predicted_avg_excess_return = lambda_0_mean_conditional_capm + \
                                  betas['beta_market'] * lambda_market_mean_conditional_capm + \
                                  betas['beta_market_x_cay'] * lambda_market_x_cay_mean_conditional_capm

    average_pricing_errors[portfolio_col] = avg_actual_excess_return - predicted_avg_excess_return

for portfolio, error in average_pricing_errors.items():
    print(f"  {portfolio}: {error:.4f}")

# Calculate GRS F-statistic
print("\n--- GRS F-statistic (Conditional CAPM) ---")

# Convert residuals to a DataFrame for covariance calculation
residuals_df = pd.DataFrame(portfolio_residuals_ts)
Sigma_res = residuals_df.cov()

# Invert Sigma_res (handle potential singularity if needed, though with real data it's usually fine)
try:
    Sigma_res_inv = np.linalg.inv(Sigma_res)
except np.linalg.LinAlgError:
    print("Could not compute inverse of residual covariance matrix. GRS test aborted.")
    grs_f_statistic = np.nan
    grs_p_value = np.nan
else:
    # Vector of alphas (intercepts from time-series regressions)
    alpha_vector = np.array([portfolio_alphas_ts[p] for p in portfolio_excess_return_cols])

    # Factors and their properties, already computed for Shanken correction on balanced panel
    # (mu_f_conditional_capm, Sigma_f_conditional_capm, Sigma_f_inv_conditional_capm)

    # Calculate the GRS statistic
    term1 = (T / N)
    term2_numerator = alpha_vector.T @ Sigma_res_inv @ alpha_vector
    term2_denominator = 1 + mu_f_conditional_capm.T @ Sigma_f_inv_conditional_capm @ mu_f_conditional_capm

    grs_f_statistic = term1 * (term2_numerator / term2_denominator)

    # Degrees of freedom for F-distribution: (N, T - N - K) where K is number of factors
    K = len(mu_f_conditional_capm) # Number of factors (market_excess_return, market_excess_return_x_cay)
    df1 = N
    df2 = T - N - K

    # Calculate p-value
    if df2 > 0: # Ensure degrees of freedom are positive
        grs_p_value = 1 - f.cdf(grs_f_statistic, df1, df2)
    else:
        grs_p_value = np.nan

print(f"GRS F-statistic: {grs_f_statistic:.4f}")
print(f"GRS p-value: {grs_p_value:.4f}")

Performing time-series regressions for Conditional CAPM (cay as multiplier) on a balanced panel...
Time-series regressions complete. Estimated Betas for Conditional CAPM (balanced panel):
BV_excess_return:
  Beta Market: 1.4290
  Beta Market x CAY: 0.4317
BN_excess_return:
  Beta Market: 1.0183
  Beta Market x CAY: 0.3187
BG_excess_return:
  Beta Market: 1.1446
  Beta Market x CAY: 0.2173
SV_excess_return:
  Beta Market: 1.1085
  Beta Market x CAY: 0.6652
SN_excess_return:
  Beta Market: 0.8690
  Beta Market x CAY: 0.5535
SG_excess_return:
  Beta Market: 1.1800
  Beta Market x CAY: 0.3682

Performing cross-sectional regressions for Conditional CAPM...
Cross-sectional regressions complete.

Computing Fama-MacBeth lambdas and standard errors for Conditional CAPM...
Fama-MacBeth Lambda Estimates (Conditional CAPM):
Mean of lambda_0: -5.7349
Standard Error of lambda_0: 1.0949
Mean of lambda_market: 0.6852
Standard Error of lambda_market: 0.8921
Mean of lambda_market_x_cay: 2.1858
Standard Error of lambda_market_x_cay: 1.4834

Applying Shanken correction...

Shanken-corrected Results (Conditional CAPM):
Shanken-corrected Standard Error of lambda_0: 5.4069
Shanken-corrected t-statistic for lambda_0: -1.0607
Shanken-corrected Standard Error of lambda_market: 4.4053
Shanken-corrected t-statistic for lambda_market: 0.1555
Shanken-corrected Standard Error of lambda_market_x_cay: 7.3251
Shanken-corrected t-statistic for lambda_market_x_cay: 0.2984

Computing average cross-sectional R-squared...
Average Cross-Sectional R-squared (Conditional CAPM): 0.6209

--- Conditional CAPM Model Results (cay as multiplier) ---
Mean lambda_market: 0.6852
Shanken-corrected t-statistic for lambda_market: 0.1555
Mean lambda_market_x_cay: 2.1858
Shanken-corrected t-statistic for lambda_market_x_cay: 0.2984
Mean lambda_0: -5.7349
Shanken-corrected t-statistic for lambda_0: -1.0607
Average cross-sectional R-squared: 0.6209

--- Average Pricing Errors (Conditional CAPM) ---
  BV_excess_return: 0.3285
  BN_excess_return: 0.3958
  BG_excess_return: -0.1773
  SV_excess_return: -0.1666
  SN_excess_return: 0.1157
  SG_excess_return: -0.4961

--- GRS F-statistic (Conditional CAPM) ---
GRS F-statistic: 1.5059
GRS p-value: 0.1831