## Data Processing

In [10]:
import pandas as pd

df_ff6 = pd.read_csv('/content/FF6.csv')
df_cay = pd.read_csv('/content/cay_index.csv')
df_market = pd.read_csv('/content/Market-Returns-Cleaned.csv')
df_consumption = pd.read_csv('/content/Consumption-Cleaned.csv')
df_ff6_factors = pd.read_csv('/content/FF6_Factors.csv')
df_income = pd.read_csv('/content/Income-Cleaned.csv')
df_risk_free = pd.read_csv('/content/Risk-Free-Cleaned.csv')

print("FF6.csv:")
display(df_ff6.head())
df_ff6.info()

print("\ncay_index.csv:")
display(df_cay.head())
df_cay.info()

print("\nMarket-Returns-Cleaned.csv:")
display(df_market.head())
df_market.info()

print("\nConsumption-Cleaned.csv:")
display(df_consumption.head())
df_consumption.info()

print("\nFF6_Factors.csv:")
display(df_ff6_factors.head())
df_ff6_factors.info()

print("\nIncome-Cleaned.csv:")
display(df_income.head())
df_income.info()

print("\nRisk-Free-Cleaned.csv:")
display(df_risk_free.head())
df_risk_free.info()

FF6.csv:

,month,Portfolios BV returns (%),Portfolios BN returns (%),Portfolios BG returns (%),Portfolios SV returns (%),Portfolios SN returns (%),Portfolios SG returns (%)
0,Apr-14,NaN,0.262471,0.172784,13.215249,6.550439,5.111012
1,May-14,NaN,23.102455,7.275463,27.552673,24.288677,15.810411
2,Jun-14,NaN,1.873951,7.745938,18.652457,16.839867,13.023586
3,Jul-14,NaN,-3.014671,1.413907,-7.500655,-2.044578,2.165995
4,Aug-14,NaN,-2.396891,4.203748,-0.729519,4.765247,4.484203

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      132 non-null    object
 1   Portfolios BV returns (%)  115 non-null    float64
 2   Portfolios BN returns (%)  132 non-null    float64
 3   Portfolios BG returns (%)  132 non-null    float64
 4   Portfolios SV returns (%)  132 non-null    float64
 5   Portfolios SN returns (%)  132 non-null    float64
 6   Portfolios SG returns (%)  132 non-null    float64
dtypes: float64(6), object(1)
memory usage: 7.3+ KB

cay_index.csv:

   month_x       cay
0  2014-04  0.057466
1  2014-05 -0.025694
2  2014-06  0.027865
3  2014-07  0.094101
4  2014-08  0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   month_x  132 non-null    object
 1   cay      132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Market-Returns-Cleaned.csv:

,month,market_return,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122
0,Apr-14,-0.006342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,May-14,0.008682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jun-14,0.015540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jul-14,-0.004266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aug-14,0.001078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Columns: 123 entries, month  to Unnamed: 122
dtypes: float64(122), object(1)
memory usage: 127.0+ KB

Consumption-Cleaned.csv:

     month  weighted_avg_consumption
0  2014-04               7208.683747
1  2014-05               7005.035044
2  2014-06               7311.807185
3  2014-07               8051.858683
4  2014-08               7449.553517

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   month                     132 non-null    object
 1   weighted_avg_consumption  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

FF6_Factors.csv:

      Date       SMB        HML       WML        MF        RF
0  2014-04  5.592209   7.810347 -3.415147  0.013121  0.701553
1  2014-05  4.340620  10.499133 -8.697000  9.950842  0.693805
2  2014-06  9.644133   5.182859  2.562922  6.929204  0.699993
3  2014-07  0.896284  -9.319494 -1.127898 -0.233564  0.700633
4  2014-08  3.732569  -4.896134  5.494075  2.452235  0.637590

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    132 non-null    object
 1   SMB     132 non-null    float64
 2   HML     132 non-null    float64
 3   WML     132 non-null    float64
 4   MF      132 non-null    float64
 5   RF      132 non-null    float64
dtypes: float64(5), object(1)
memory usage: 6.3+ KB

Income-Cleaned.csv:

     month  national_weighted_avg_income
0  2014-04                   12811.15146
1  2014-05                   14071.83162
2  2014-06                   13803.13302
3  2014-07                   14442.45259
4  2014-08                   13169.36297

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   month                         132 non-null    object
 1   national_weighted_avg_income  132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

Risk-Free-Cleaned.csv:

     month   Yeild
0  2014-04  8.8550
1  2014-05  8.6456
2  2014-06  8.5619
3  2014-07  8.6456
4  2014-08  8.6038

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   132 non-null    object
 1   Yeild   132 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.2+ KB

In [12]:
df_ff6['Date'] = pd.to_datetime(df_ff6['month'], format='%b-%y')
df_ff6_factors['Date'] = pd.to_datetime(df_ff6_factors['Date'], format='%Y-%m')
df_market['month '] = pd.to_datetime(df_market['month '], format='%b-%y')
df_risk_free['month'] = pd.to_datetime(df_risk_free['month'], format='%Y-%m')
df_cay['month_x'] = pd.to_datetime(df_cay['month_x'], format='%Y-%m')
df_consumption['month'] = pd.to_datetime(df_consumption['month'], format='%Y-%m')
df_income['month'] = pd.to_datetime(df_income['month'], format='%Y-%m')

merged_df = pd.merge(df_ff6, df_risk_free, left_on='Date', right_on='month', how='inner')
merged_df = pd.merge(merged_df, df_ff6_factors, on='Date', how='inner')
merged_df = pd.merge(merged_df, df_market[['month ', 'market_return']], left_on='Date', right_on='month ', how='inner')

portfolio_cols = ['Portfolios BV returns (%)', 'Portfolios BN returns (%)', 'Portfolios BG returns (%)', 'Portfolios SV returns (%)', 'Portfolios SN returns (%)', 'Portfolios SG returns (%)']
for col in portfolio_cols:
    merged_df[f'{col}_excess'] = merged_df[col] - merged_df['Yeild']

merged_df['market_return_excess'] = merged_df['market_return'] - merged_df['Yeild']

merged_df.rename(columns={'Date': 'date', 'month_x': 'date', 'month': 'date', 'month ': 'date',
                          'Portfolios BV returns (%)_excess': 'BV_excess_return',
                          'Portfolios BN returns (%)_excess': 'BN_excess_return',
                          'Portfolios BG returns (%)_excess': 'BG_excess_return',
                          'Portfolios SV returns (%)_excess': 'SV_excess_return',
                          'Portfolios SN returns (%)_excess': 'SN_excess_return',
                          'Portfolios SG returns (%)_excess': 'SG_excess_return',
                          'market_return_excess': 'market_excess_return',
                          'SMB': 'smb', 'HML': 'hml', 'WML': 'wml', 'MF': 'mf', 'RF': 'rf',
                          'weighted_avg_consumption': 'consumption',
                          'national_weighted_avg_income': 'income',
                          'cay': 'cay_index'}, inplace=True)


columns_to_drop = portfolio_cols + ['market_return', 'Yeild']
merged_df.drop(columns=columns_to_drop, inplace=True)

display(merged_df.head())
merged_df.info()

,date,date,month_y,smb,hml,wml,mf,rf,date,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return
0,Apr-14,2014-04-01,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,2014-04-01,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342
1,May-14,2014-05-01,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,2014-05-01,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918
2,Jun-14,2014-06-01,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,2014-06-01,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360
3,Jul-14,2014-07-01,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,2014-07-01,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866
4,Aug-14,2014-08-01,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,2014-08-01,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  132 non-null    object
 1   date                  132 non-null    datetime64[ns]
 2   month_y               132 non-null    datetime64[ns]
 3   smb                   132 non-null    float64
 4   hml                   132 non-null    float64
 5   wml                   132 non-null    float64
 6   mf                    132 non-null    float64
 7   rf                    132 non-null    float64
 8   date                  132 non-null    datetime64[ns]
 9   BV_excess_return      115 non-null    float64
 10  BN_excess_return      132 non-null    float64
 11  BG_excess_return      132 non-null    float64
 12  SV_excess_return      132 non-null    float64
 13  SN_excess_return      132 non-null    float64
 14  SG_excess_return      132 non-null    float64
 15  market_excess_return  132 non-null    float64
dtypes: datetime64[ns](3), float64(12), object(1)
memory usage: 16.6+ KB

In [16]:
df_income.rename(columns={'month': 'date'}, inplace=True)
df_consumption.rename(columns={'month': 'date'}, inplace=True)

merged_df = merged_df.loc[:,~merged_df.columns.duplicated()]

# Explicitly convert the 'date' column in merged_df to datetime with the correct format
merged_df['date'] = pd.to_datetime(merged_df['date'], format='%b-%y')

merged_df = pd.merge(merged_df, df_income, on='date', how='inner')
merged_df = pd.merge(merged_df, df_consumption, on='date', how='inner')

print(merged_df.columns)

merged_df['income_growth'] = merged_df['national_weighted_avg_income'].pct_change() * 100
merged_df['consumption_growth'] = merged_df['weighted_avg_consumption'].pct_change() * 100

display(merged_df.head())

Index(['date', 'month_y', 'smb', 'hml', 'wml', 'mf', 'rf', 'BV_excess_return',
       'BN_excess_return', 'BG_excess_return', 'SV_excess_return',
       'SN_excess_return', 'SG_excess_return', 'market_excess_return',
       'national_weighted_avg_income', 'weighted_avg_consumption'],
      dtype='object')

,date,month_y,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth
0,2014-04-01,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN
1,2014-05-01,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047
2,2014-06-01,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309
3,2014-07-01,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321
4,2014-08-01,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325

In [17]:
merged_df = pd.merge(merged_df, df_cay, left_on='date', right_on='month_x', how='inner')

display(merged_df.head())
merged_df.info()

,date,month_y,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,SV_excess_return,SN_excess_return,SG_excess_return,market_excess_return,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay
0,2014-04-01,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,4.360249,-2.304561,-3.743988,-8.861342,12811.15146,7208.683747,NaN,NaN,2014-04-01,0.057466
1,2014-05-01,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,18.907073,15.643077,7.164811,-8.636918,14071.83162,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694
2,2014-06-01,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,10.090557,8.277967,4.461686,-8.546360,13803.13302,7311.807185,-1.909479,4.379309,2014-06-01,0.027865
3,2014-07-01,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,-16.146255,-10.690178,-6.479605,-8.649866,14442.45259,8051.858683,4.631699,10.121321,2014-07-01,0.094101
4,2014-08-01,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,-9.333319,-3.838553,-4.119597,-8.602722,13169.36297,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          132 non-null    datetime64[ns]
 1   month_y                       132 non-null    datetime64[ns]
 2   smb                           132 non-null    float64
 3   hml                           132 non-null    float64
 4   wml                           132 non-null    float64
 5   mf                            132 non-null    float64
 6   rf                            132 non-null    float64
 7   BV_excess_return              115 non-null    float64
 8   BN_excess_return              132 non-null    float64
 9   BG_excess_return              132 non-null    float64
 10  SV_excess_return              132 non-null    float64
 11  SN_excess_return              132 non-null    float64
 12  SG_excess_return              132 non-null    float64
 13  market_excess_return          132 non-null    float64
 14  national_weighted_avg_income  132 non-null    float64
 15  weighted_avg_consumption      132 non-null    float64
 16  income_growth                 131 non-null    float64
 17  consumption_growth            131 non-null    float64
 18  month_x                       132 non-null    datetime64[ns]
 19  cay                           132 non-null    float64
dtypes: datetime64[ns](3), float64(17)
memory usage: 20.8 KB

In [18]:
print(merged_df.columns)

Index(['date', 'month_y', 'smb', 'hml', 'wml', 'mf', 'rf', 'BV_excess_return',
       'BN_excess_return', 'BG_excess_return', 'SV_excess_return',
       'SN_excess_return', 'SG_excess_return', 'market_excess_return',
       'national_weighted_avg_income', 'weighted_avg_consumption',
       'income_growth', 'consumption_growth', 'month_x', 'cay'],
      dtype='object')

In [23]:
macro_vars = ['income_growth', 'consumption_growth', 'cay']

for var in macro_vars:
    mean = merged_df[var].mean()
    std = merged_df[var].std()
    merged_df[f'{var}_standardized'] = (merged_df[var] - mean) / std

# Add the interaction term: consumption growth x standardized cay
merged_df['consumption_growth_x_cay_standardized'] = merged_df['consumption_growth'] * merged_df['cay_standardized']

display(merged_df.head())

,date,month_y,smb,hml,wml,mf,rf,BV_excess_return,BN_excess_return,BG_excess_return,...,national_weighted_avg_income,weighted_avg_consumption,income_growth,consumption_growth,month_x,cay,income_growth_standardized,consumption_growth_standardized,cay_standardized,consumption_growth_x_cay_standardized
0,2014-04-01,2014-04-01,5.592209,7.810347,-3.415147,0.013121,0.701553,NaN,-8.592529,-8.682216,...,12811.15146,7208.683747,NaN,NaN,2014-04-01,0.057466,NaN,NaN,0.278844,NaN
1,2014-05-01,2014-05-01,4.340620,10.499133,-8.697000,9.950842,0.693805,NaN,14.456855,-1.370137,...,14071.83162,7005.035044,9.840491,-2.825047,2014-05-01,-0.025694,1.708192,-0.349998,-0.124676,0.352214
2,2014-06-01,2014-06-01,9.644133,5.182859,2.562922,6.929204,0.699993,NaN,-6.687949,-0.815962,...,13803.13302,7311.807185,-1.909479,4.379309,2014-06-01,0.027865,-0.534120,0.271423,0.135212,0.592137
3,2014-07-01,2014-07-01,0.896284,-9.319494,-1.127898,-0.233564,0.700633,NaN,-11.660271,-7.231693,...,14442.45259,8051.858683,4.631699,10.121321,2014-07-01,0.094101,0.714170,0.766707,0.456614,4.621536
4,2014-08-01,2014-08-01,3.732569,-4.896134,5.494075,2.452235,0.637590,NaN,-11.000691,-4.400052,...,13169.36297,7449.553517,-8.814913,-7.480325,2014-08-01,0.074530,-1.851922,-0.751545,0.361647,-2.705239

## Model

In [30]:
import statsmodels.api as sm
import numpy as np

# 1. Define a list containing the names of the portfolio excess return columns.
portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

# 2. Initialize an empty dictionary to store the estimated betas for each portfolio.
portfolio_betas_ccapm_cay = {}

# 3. Define the independent variables for the time-series regression as 'consumption_growth', 'consumption_growth_x_cay_standardized' and 'cay_standardized'
X_ts = merged_df[['consumption_growth', 'consumption_growth_x_cay_standardized', 'cay_standardized']].copy()

# 4. Add a constant term to the independent variables DataFrame using sm.add_constant.
X_ts = sm.add_constant(X_ts)

# 5. Iterate through each portfolio excess return column:
print("Performing time-series regressions for CCAPM with consumption growth, consumption growth x cay interaction, and cay...")
for portfolio_col in portfolio_excess_return_cols:
    # a. Define the dependent variable as the current portfolio's excess return.
    y_ts = merged_df[portfolio_col]

    # b. Drop rows with NaN values in the dependent variable and the corresponding rows in the independent variables DataFrame.
    valid_indices = y_ts.dropna().index
    y_ts_cleaned = y_ts.loc[valid_indices]
    X_ts_cleaned = X_ts.loc[valid_indices]

    # Drop rows with NaN values in X_ts_cleaned before fitting the model
    valid_X_indices = X_ts_cleaned.dropna().index
    y_ts_cleaned = y_ts_cleaned.loc[valid_X_indices]
    X_ts_cleaned = X_ts_cleaned.loc[valid_X_indices]


    if not X_ts_cleaned.empty and not y_ts_cleaned.empty:
        # c. Fit an OLS model using sm.OLS with the cleaned dependent and independent variables.
        model_ts = sm.OLS(y_ts_cleaned, X_ts_cleaned)
        results_ts = model_ts.fit()

        # d. Store the estimated coefficients for 'consumption_growth', 'consumption_growth_x_cay_standardized' and 'cay_standardized'
        portfolio_betas_ccapm_cay[portfolio_col] = {
            'beta_consumption': results_ts.params['consumption_growth'],
            'beta_consumption_x_cay': results_ts.params['consumption_growth_x_cay_standardized'],
            'beta_cay': results_ts.params['cay_standardized']
        }
    else:
         # Handle cases where there are no valid data points for regression
        portfolio_betas_ccapm_cay[portfolio_col] = {
            'beta_consumption': np.nan,
            'beta_consumption_x_cay': np.nan,
            'beta_cay': np.nan
        }

# 6. Print the estimated betas for each portfolio.
print("Time-series regressions complete. Estimated Betas for CCAPM with consumption growth, consumption growth x cay interaction, and cay:")
for portfolio, betas in portfolio_betas_ccapm_cay.items():
    print(f"{portfolio}:")
    print(f"  Beta Consumption: {betas['beta_consumption']:.4f}")
    print(f"  Beta Consumption x CAY: {betas['beta_consumption_x_cay']:.4f}")
    print(f"  Beta CAY: {betas['beta_cay']:.4f}")

Performing time-series regressions for CCAPM with consumption growth, consumption growth x cay interaction, and cay...
Time-series regressions complete. Estimated Betas for CCAPM with consumption growth, consumption growth x cay interaction, and cay:
BV_excess_return:
  Beta Consumption: 0.0549
  Beta Consumption x CAY: 0.0416
  Beta CAY: -2.8847
BN_excess_return:
  Beta Consumption: 0.0920
  Beta Consumption x CAY: 0.0623
  Beta CAY: -2.1312
BG_excess_return:
  Beta Consumption: 0.0741
  Beta Consumption x CAY: 0.0246
  Beta CAY: -1.8307
SV_excess_return:
  Beta Consumption: 0.1489
  Beta Consumption x CAY: 0.0680
  Beta CAY: -3.7740
SN_excess_return:
  Beta Consumption: 0.1132
  Beta Consumption x CAY: 0.0450
  Beta CAY: -3.1608
SG_excess_return:
  Beta Consumption: 0.1157
  Beta Consumption x CAY: 0.0473
  Beta CAY: -2.5384

In [34]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy.stats import chi2

# Create a DataFrame of the estimated betas for cross-sectional regression
betas_df_ccapm_cay = pd.DataFrame.from_dict(portfolio_betas_ccapm_cay, orient='index')
betas_df_ccapm_cay = sm.add_constant(betas_df_ccapm_cay) # Add constant for lambda_0

# Perform cross-sectional regressions
print("\nPerforming cross-sectional regressions for CCAPM with consumption growth, consumption growth x cay interaction, and cay...")
lambda_estimates_ccapm_cay = []
all_cs_residuals = [] # List to store cross-sectional residuals for each time period

portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

for index, row in merged_df.iterrows():
    y_cs = row[portfolio_excess_return_cols]

    # Drop NaN values from y_cs and get the corresponding betas from betas_df_ccapm_cay
    valid_portfolios = y_cs.dropna().index
    y_cs_cleaned = y_cs.loc[valid_portfolios].astype(float)

    # Select the betas corresponding to the valid portfolios
    betas_for_cs = betas_df_ccapm_cay.loc[valid_portfolios].astype(float)

    # Ensure there are enough valid data points and betas for regression (at least 4 for intercept and three betas)
    if len(valid_portfolios) >= 4 and not betas_for_cs.empty:
        try:
            model_cs = sm.OLS(y_cs_cleaned, betas_for_cs)
            results_cs = model_cs.fit()
            # Ensure the number of parameters is 4 before appending (lambda_0, lambda_consumption, lambda_consumption_x_cay, lambda_cay)
            if len(results_cs.params) == 4:
                lambda_estimates_ccapm_cay.append(results_cs.params.tolist())
                # Store residuals for chi-square calculation
                residuals_series = results_cs.resid.rename(row.name)
                all_cs_residuals.append(residuals_series)
            else:
                 # Append NaNs if the number of parameters is not as expected
                lambda_estimates_ccapm_cay.append([np.nan, np.nan, np.nan, np.nan])
        except Exception as e:
            # Handle potential errors during regression
            print(f"Regression error at index {index}: {e}")
            lambda_estimates_ccapm_cay.append([np.nan, np.nan, np.nan, np.nan])
    else:
        # Append NaNs if regression cannot be performed
        lambda_estimates_ccapm_cay.append([np.nan, np.nan, np.nan, np.nan])

lambda_df_ccapm_cay = pd.DataFrame(lambda_estimates_ccapm_cay, columns=['lambda_0', 'lambda_consumption', 'lambda_consumption_x_cay', 'lambda_cay'])
print("Cross-sectional regressions complete.")

# Create DataFrame of all cross-sectional residuals
df_all_cs_residuals = pd.DataFrame(all_cs_residuals)

# 3. Compute Fama–MacBeth lambdas and standard errors
print("\nComputing Fama-MacBeth lambdas and standard errors for CCAPM with consumption growth, consumption growth x cay interaction, and cay...")
lambda_0_mean_ccapm_cay = lambda_df_ccapm_cay['lambda_0'].mean()
lambda_0_sem_ccapm_cay = lambda_df_ccapm_cay['lambda_0'].sem()
lambda_consumption_mean_ccapm_cay = lambda_df_ccapm_cay['lambda_consumption'].mean()
lambda_consumption_sem_ccapm_cay = lambda_df_ccapm_cay['lambda_consumption'].sem()
lambda_consumption_x_cay_mean_ccapm_cay = lambda_df_ccapm_cay['lambda_consumption_x_cay'].mean()
lambda_consumption_x_cay_sem_ccapm_cay = lambda_df_ccapm_cay['lambda_consumption_x_cay'].sem()
lambda_cay_mean_ccapm_cay = lambda_df_ccapm_cay['lambda_cay'].mean()
lambda_cay_sem_ccapm_cay = lambda_df_ccapm_cay['lambda_cay'].sem()


print("Fama-MacBeth Lambda Estimates (CCAPM with consumption growth, consumption growth x cay interaction, and cay):")
print(f"Mean of lambda_0: {lambda_0_mean_ccapm_cay:.4f}")
print(f"Standard Error of lambda_0: {lambda_0_sem_ccapm_cay:.4f}")
print(f"Mean of lambda_consumption: {lambda_consumption_mean_ccapm_cay:.4f}")
print(f"Standard Error of lambda_consumption: {lambda_consumption_sem_ccapm_cay:.4f}")
print(f"Mean of lambda_consumption_x_cay: {lambda_consumption_x_cay_mean_ccapm_cay:.4f}")
print(f"Standard Error of lambda_consumption_x_cay: {lambda_consumption_x_cay_sem_ccapm_cay:.4f}")
print(f"Mean of lambda_cay: {lambda_cay_mean_ccapm_cay:.4f}")
print(f"Standard Error of lambda_cay: {lambda_cay_sem_ccapm_cay:.4f}")


# 4. Apply Shanken correction
print("\nApplying Shanken correction...")
# 1. Calculate the mean vector and covariance matrix of the factors
# Factors are consumption growth, consumption_growth_x_cay_standardized, and cay_standardized
factors_ccapm_cay_shanken = merged_df[['consumption_growth', 'consumption_growth_x_cay_standardized', 'cay_standardized']].dropna()
mu_f_ccapm_cay = factors_ccapm_cay_shanken.mean().values
Sigma_f_ccapm_cay = factors_ccapm_cay_shanken.cov().values

# 2. Calculate the Shanken correction factor
# Formula: (1 + mu_f' * inv(Sigma_f) * mu_f)
try:
    Sigma_f_inv_ccapm_cay = np.linalg.inv(Sigma_f_ccapm_cay)
    shanken_correction_factor_ccapm_cay = (1 + mu_f_ccapm_cay.T @ Sigma_f_inv_ccapm_cay @ mu_f_ccapm_cay)
except np.linalg.LinAlgError:
    print("Could not compute inverse of the covariance matrix. Skipping Shanken correction.")
    shanken_correction_factor_ccapm_cay = np.nan


if not np.isnan(shanken_correction_factor_ccapm_cay):
    # 3. Multiply the squared standard errors of the Fama-MacBeth lambdas by the Shanken correction factor
    lambda_0_shanken_variance_ccapm_cay = (lambda_0_sem_ccapm_cay**2) * shanken_correction_factor_ccapm_cay
    lambda_consumption_shanken_variance_ccapm_cay = (lambda_consumption_sem_ccapm_cay**2) * shanken_correction_factor_ccapm_cay
    lambda_consumption_x_cay_shanken_variance_ccapm_cay = (lambda_consumption_x_cay_sem_ccapm_cay**2) * shanken_correction_factor_ccapm_cay
    lambda_cay_shanken_variance_ccapm_cay = (lambda_cay_sem_ccapm_cay**2) * shanken_correction_factor_ccapm_cay


    # 4. Take the square root of the Shanken-corrected variances to get the Shanken-corrected standard errors
    lambda_0_shanken_sem_ccapm_cay = np.sqrt(lambda_0_shanken_variance_ccapm_cay)
    lambda_consumption_shanken_sem_ccapm_cay = np.sqrt(lambda_consumption_shanken_variance_ccapm_cay)
    lambda_consumption_x_cay_shanken_sem_ccapm_cay = np.sqrt(lambda_consumption_x_cay_shanken_variance_ccapm_cay)
    lambda_cay_shanken_sem_ccapm_cay = np.sqrt(lambda_cay_shanken_variance_ccapm_cay)


    # 5. Calculate the t-statistics using the mean lambdas and Shanken-corrected standard errors
    lambda_0_shanken_tstat_ccapm_cay = lambda_0_mean_ccapm_cay / lambda_0_shanken_sem_ccapm_cay
    lambda_consumption_shanken_tstat_ccapm_cay = lambda_consumption_mean_ccapm_cay / lambda_consumption_shanken_sem_ccapm_cay
    lambda_consumption_x_cay_shanken_tstat_ccapm_cay = lambda_consumption_x_cay_mean_ccapm_cay / lambda_consumption_x_cay_shanken_sem_ccapm_cay
    lambda_cay_shanken_tstat_ccapm_cay = lambda_cay_mean_ccapm_cay / lambda_cay_shanken_sem_ccapm_cay


    # 6. Print the Shanken-corrected standard errors and t-statistics
    print("\nShanken-corrected Results (CCAPM with consumption growth, consumption growth x cay interaction, and cay):")
    print(f"Shanken-corrected Standard Error of lambda_0: {lambda_0_shanken_sem_ccapm_cay:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_0: {lambda_0_shanken_tstat_ccapm_cay:.4f}")
    print(f"Shanken-corrected Standard Error of lambda_consumption: {lambda_consumption_shanken_sem_ccapm_cay:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_consumption: {lambda_consumption_shanken_tstat_ccapm_cay:.4f}")
    print(f"Shanken-corrected Standard Error of lambda_consumption_x_cay: {lambda_consumption_x_cay_shanken_sem_ccapm_cay:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_consumption_x_cay: {lambda_consumption_x_cay_shanken_tstat_ccapm_cay:.4f}")
    print(f"Shanken-corrected Standard Error of lambda_cay: {lambda_cay_shanken_sem_ccapm_cay:.4f}")
    print(f"Shanken-corrected t-statistic for lambda_cay: {lambda_cay_shanken_tstat_ccapm_cay:.4f}")

else:
    print("\nShanken correction could not be applied.")

# 5. Compute cross-sectional R²
print("\nComputing average cross-sectional R-squared...")
cs_r_squared_values_ccapm_cay = []

for index, row in merged_df.iterrows():
    y_cs = row[portfolio_excess_return_cols]

    valid_portfolios = y_cs.dropna().index
    y_cs_cleaned = y_cs.loc[valid_portfolios].astype(float)

    betas_for_cs = betas_df_ccapm_cay.loc[valid_portfolios].astype(float)

    if len(valid_portfolios) >= 4 and not betas_for_cs.empty:
        try:
            model_cs = sm.OLS(y_cs_cleaned, betas_for_cs)
            results_cs = model_cs.fit()
            if len(results_cs.params) == 4:
                 # Calculate R-squared for the cross-sectional regression
                y_cs_mean = y_cs_cleaned.mean()
                ss_total = ((y_cs_cleaned - y_cs_mean) ** 2).sum()
                # Calculate predicted values using the cross-sectional regression results
                predicted_y_cs = results_cs.predict(betas_for_cs)
                ss_residual = ((y_cs_cleaned - predicted_y_cs) ** 2).sum()
                # Avoid division by zero if ss_total is zero
                if ss_total > 0:
                    cs_r_squared = 1 - (ss_residual / ss_total)
                    cs_r_squared_values_ccapm_cay.append(cs_r_squared)
                else:
                    cs_r_squared_values_ccapm_cay.append(np.nan) # Append NaN if ss_total is zero
            else:
                cs_r_squared_values_ccapm_cay.append(np.nan)
        except Exception as e:
            print(f"Regression error at index {index}: {e}")
            cs_r_squared_values_ccapm_cay.append(np.nan)
    else:
        cs_r_squared_values_ccapm_cay.append(np.nan)


average_cs_r_squared_ccapm_cay = np.nanmean(cs_r_squared_values_ccapm_cay)

print(f"Average Cross-Sectional R-squared (CCAPM with consumption growth, consumption growth x cay interaction, and cay): {average_cs_r_squared_ccapm_cay:.4f}")


# 6. Report results (Summary)
print("\n--- CCAPM with consumption growth, consumption growth x cay interaction, and cay Model Results ---")
print(f"Mean lambda_consumption: {lambda_consumption_mean_ccapm_cay:.4f}")
if not np.isnan(shanken_correction_factor_ccapm_cay):
    print(f"Shanken-corrected t-statistic for lambda_consumption: {lambda_consumption_shanken_tstat_ccapm_cay:.4f}")
else:
     print("Shanken-corrected t-statistic for lambda_consumption: N/A (Shanken correction not applied)")

print(f"Mean lambda_consumption_x_cay: {lambda_consumption_x_cay_mean_ccapm_cay:.4f}")
if not np.isnan(shanken_correction_factor_ccapm_cay):
    print(f"Shanken-corrected t-statistic for lambda_consumption_x_cay: {lambda_consumption_x_cay_shanken_tstat_ccapm_cay:.4f}")
else:
    print("Shanken-corrected t-statistic for lambda_consumption_x_cay: N/A (Shanken correction not applied)")

print(f"Mean lambda_cay: {lambda_cay_mean_ccapm_cay:.4f}")
if not np.isnan(shanken_correction_factor_ccapm_cay):
    print(f"Shanken-corrected t-statistic for lambda_cay: {lambda_cay_shanken_tstat_ccapm_cay:.4f}")
else:
    print("Shanken-corrected t-statistic for lambda_cay: N/A (Shanken correction not applied)")

print(f"Mean lambda_0: {lambda_0_mean_ccapm_cay:.4f}")
if not np.isnan(shanken_correction_factor_ccapm_cay):
    print(f"Shanken-corrected t-statistic for lambda_0: {lambda_0_shanken_tstat_ccapm_cay:.4f}")
else:
    print("Shanken-corrected t-statistic for lambda_0: N/A (Shanken correction not applied)")


print(f"Average cross-sectional R-squared: {average_cs_r_squared_ccapm_cay:.4f}")

print("\n--- CCAPM with consumption growth, consumption growth x cay interaction, and cay Summary ---")
print("Key Findings:")
print(f"* The estimated betas for the six portfolios show varying sensitivities to consumption growth, the consumption growth x cay interaction term, and cay.")
print(f"* The mean estimated consumption risk premium (lambda_consumption) is {lambda_consumption_mean_ccapm_cay:.4f}.")
print(f"* The mean estimated consumption growth x cay risk premium (lambda_consumption_x_cay) is {lambda_consumption_x_cay_mean_ccapm_cay:.4f}.")
print(f"* The mean estimated cay risk premium (lambda_cay) is {lambda_cay_mean_ccapm_cay:.4f}.")
print(f"* The mean estimated zero-beta rate (lambda_0) is {lambda_0_mean_ccapm_cay:.4f}.")

if not np.isnan(shanken_correction_factor_ccapm_cay):
    print("* Shanken-corrected t-statistics indicate the statistical significance of the estimated risk premia.")
    print(f"  - Consumption Risk Premium t-statistic: {lambda_consumption_shanken_tstat_ccapm_cay:.4f}")
    print(f"  - Consumption x CAY Risk Premium t-statistic: {lambda_consumption_x_cay_shanken_tstat_ccapm_cay:.4f}")
    print(f"  - CAY Risk Premium t-statistic: {lambda_cay_shanken_tstat_ccapm_cay:.4f}")
    print(f"  - Zero-Beta Rate t-statistic: {lambda_0_shanken_tstat_ccapm_cay:.4f}")
else:
    print("* Shanken correction could not be applied due to issues with the covariance matrix.")

print(f"* The average cross-sectional R-squared of {average_cs_r_squared_ccapm_cay:.4f} suggests the proportion of the cross-sectional variation in portfolio excess returns explained by the model.")

print("\nNext Steps:")
print("- Summarize all model results in a comprehensive table.")

Performing cross-sectional regressions for CCAPM with consumption growth, consumption growth x cay interaction, and cay...
Cross-sectional regressions complete.

Computing Fama-MacBeth lambdas and standard errors for CCAPM with consumption growth, consumption growth x cay interaction, and cay...
Fama-MacBeth Lambda Estimates (CCAPM with consumption growth, consumption growth x cay interaction, and cay):
Mean of lambda_0: -5.7916
Standard Error of lambda_0: 0.5836
Mean of lambda_consumption: -5.8858
Standard Error of lambda_consumption: 9.3170
Mean of lambda_consumption_x_cay: 6.7340
Standard Error of lambda_consumption_x_cay: 11.0592
Mean of lambda_cay: -0.6495
Standard Error of lambda_cay: 0.3683

Applying Shanken correction...

Shanken-corrected Results (CCAPM with consumption growth, consumption growth x cay interaction, and cay):
Shanken-corrected Standard Error of lambda_0: 0.6024
Shanken-corrected t-statistic for lambda_0: -9.6149
Shanken-corrected Standard Error of lambda_consumption: 9.6168
Shanken-corrected t-statistic for lambda_consumption: -0.6120
Shanken-corrected Standard Error of lambda_consumption_x_cay: 11.4150
Shanken-corrected t-statistic for lambda_consumption_x_cay: 0.5899
Shanken-corrected Standard Error of lambda_cay: 0.3802
Shanken-corrected t-statistic for lambda_cay: -1.7083

Computing average cross-sectional R-squared...
Average Cross-Sectional R-squared (CCAPM with consumption growth, consumption growth x cay interaction, and cay): 0.8777

--- CCAPM with consumption growth, consumption growth x cay interaction, and cay Model Results ---
Mean lambda_consumption: -5.8858
Shanken-corrected t-statistic for lambda_consumption: -0.6120
Mean lambda_consumption_x_cay: 6.7340
Shanken-corrected t-statistic for lambda_consumption_x_cay: 0.5899
Mean lambda_cay: -0.6495
Shanken-corrected t-statistic for lambda_cay: -1.7083
Mean lambda_0: -5.7916
Shanken-corrected t-statistic for lambda_0: -9.6149
Average cross-sectional R-squared: 0.8777

--- CCAPM with consumption growth, consumption growth x cay interaction, and cay Summary ---
Key Findings:
* The estimated betas for the six portfolios show varying sensitivities to consumption growth, the consumption growth x cay interaction term, and cay.
* The mean estimated consumption risk premium (lambda_consumption) is -5.8858.
* The mean estimated consumption growth x cay risk premium (lambda_consumption_x_cay) is 6.7340.
* The mean estimated cay risk premium (lambda_cay) is -0.6495.
* The mean estimated zero-beta rate (lambda_0) is -5.7916.
* Shanken-corrected t-statistics indicate the statistical significance of the estimated risk premia.
  - Consumption Risk Premium t-statistic: -0.6120
  - Consumption x CAY Risk Premium t-statistic: 0.5899
  - CAY Risk Premium t-statistic: -1.7083
  - Zero-Beta Rate t-statistic: -9.6149
* The average cross-sectional R-squared of 0.8777 suggests the proportion of the cross-sectional variation in portfolio excess returns explained by the model.

Next Steps:
- Summarize all model results in a comprehensive table.

In [36]:
results_summary = {
    'Model': ['CCAPM (Consumption Growth, Interaction with CAY & CAY)'],
    'Mean Lambda Consumption': [lambda_consumption_mean_ccapm_cay],
    'T-stat Lambda Consumption (Shanken)': [lambda_consumption_shanken_tstat_ccapm_cay],
    'Mean Lambda Consumption x CAY': [lambda_consumption_x_cay_mean_ccapm_cay],
    'T-stat Lambda Consumption x CAY (Shanken)': [lambda_consumption_x_cay_shanken_tstat_ccapm_cay],
    'Mean Lambda CAY': [lambda_cay_mean_ccapm_cay],
    'T-stat Lambda CAY (Shanken)': [lambda_cay_shanken_tstat_ccapm_cay],
    'Mean Lambda 0 (Zero-Beta)': [lambda_0_mean_ccapm_cay],
    'T-stat Lambda 0 (Shanken)': [lambda_0_shanken_tstat_ccapm_cay],
    'Average CS R-squared': [average_cs_r_squared_ccapm_cay],
    'Overall Mean Pricing Error': [overall_mean_pricing_error],
    'Chi-square Statistic (Joint Errors)': [chi_square_stat],
    'P-value (Chi-square)': [p_value_chi2]
}

df_results_summary = pd.DataFrame(results_summary)
display(df_results_summary.round(4))

print("\nComprehensive Summary Table of CCAPM Model Results:")
print("This table presents the key findings from the Consumption CAPM model, including the mean estimates for the risk premia (lambdas) and their Shanken-corrected t-statistics, along with the model's explanatory power (average cross-sectional R-squared), overall mean pricing error, and chi-square test results for pricing errors.")

,Model,Mean Lambda Consumption,T-stat Lambda Consumption (Shanken),Mean Lambda Consumption x CAY,T-stat Lambda Consumption x CAY (Shanken),Mean Lambda CAY,T-stat Lambda CAY (Shanken),Mean Lambda 0 (Zero-Beta),T-stat Lambda 0 (Shanken),Average CS R-squared,Overall Mean Pricing Error,Chi-square Statistic (Joint Errors),P-value (Chi-square)
0,"CCAPM (Consumption Growth, Interaction with CA...",-5.8858,-0.612,6.734,0.5899,-0.6495,-1.7083,-5.7916,-9.6149,0.8777,0.0914,-2.588884e+17,1.0

Comprehensive Summary Table of CCAPM Model Results:
This table presents the key findings from the Consumption CAPM model, including the mean estimates for the risk premia (lambdas) and their Shanken-corrected t-statistics, along with the model's explanatory power (average cross-sectional R-squared), overall mean pricing error, and chi-square test results for pricing errors.

## Mean Pricing Error

In [35]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy.stats import chi2

# 1. Get the estimated lambdas (mean risk premia) from the Fama-MacBeth second-pass regression
lambda_0 = lambda_0_mean_ccapm_cay
lambda_consumption = lambda_consumption_mean_ccapm_cay
lambda_consumption_x_cay = lambda_consumption_x_cay_mean_ccapm_cay
lambda_cay = lambda_cay_mean_ccapm_cay

# 2. Get the estimated betas for each portfolio from the first-pass time-series regressions
#    This is already stored in the 'portfolio_betas_ccapm_cay' dictionary

# 3. Calculate the Mean Pricing Error (MPE) for each portfolio
mean_pricing_errors = {}
portfolio_excess_return_cols = [
    'BV_excess_return', 'BN_excess_return', 'BG_excess_return',
    'SV_excess_return', 'SN_excess_return', 'SG_excess_return'
]

for portfolio_col in portfolio_excess_return_cols:
    # a. Get the betas for the current portfolio
    betas = portfolio_betas_ccapm_cay.get(portfolio_col, {})
    beta_consumption = betas.get('beta_consumption', np.nan)
    beta_consumption_x_cay = betas.get('beta_consumption_x_cay', np.nan)
    beta_cay = betas.get('beta_cay', np.nan)

    # Only proceed if all necessary betas are available
    if not np.isnan(beta_consumption) and not np.isnan(beta_consumption_x_cay) and not np.isnan(beta_cay):
        # b. Calculate the predicted excess return
        predicted_excess_return = lambda_0 + \
                                  beta_consumption * lambda_consumption + \
                                  beta_consumption_x_cay * lambda_consumption_x_cay + \
                                  beta_cay * lambda_cay

        # c. Calculate the average realized excess return for the portfolio
        #    Need to drop NaNs before calculating the mean, as BV_excess_return had NaNs
        average_realized_excess_return = merged_df[portfolio_col].mean()

        # d. Calculate the pricing error
        pricing_error = average_realized_excess_return - predicted_excess_return
        mean_pricing_errors[portfolio_col] = pricing_error
    else:
        mean_pricing_errors[portfolio_col] = np.nan

# 4. Display the Mean Pricing Errors
print("\nMean Pricing Errors for each portfolio:")
for portfolio, mpe in mean_pricing_errors.items():
    print(f"  {portfolio}: {mpe:.4f}")

# Create a DataFrame for better display of individual MPEs
df_mpe = pd.DataFrame(mean_pricing_errors.items(), columns=['Portfolio', 'Mean Pricing Error'])
df_mpe.set_index('Portfolio', inplace=True)
print("\nMean Pricing Errors (DataFrame):")
display(df_mpe.round(4))

# 5. Calculate Overall Mean Pricing Error
overall_mean_pricing_error = df_mpe['Mean Pricing Error'].mean()
print(f"\nOverall Mean Pricing Error across all portfolios: {overall_mean_pricing_error:.4f}")

# 6. Calculate Chi-square statistic for the errors (GRS-like test for joint significance of alphas)
# This uses the time-series of cross-sectional residuals collected in df_all_cs_residuals
if 'df_all_cs_residuals' in globals() and not df_all_cs_residuals.empty:
    try:
        # Ensure df_all_cs_residuals is aligned with the portfolios for which MPEs are calculated
        # Filter residuals to include only portfolios with calculated MPEs
        valid_portfolios_in_mpe = [p for p, mpe in mean_pricing_errors.items() if not np.isnan(mpe)]
        df_all_cs_residuals_filtered = df_all_cs_residuals[valid_portfolios_in_mpe].dropna()

        if not df_all_cs_residuals_filtered.empty:
            # Covariance matrix of the cross-sectional residuals
            cov_epsilon = df_all_cs_residuals_filtered.cov()

            # Vector of mean pricing errors for valid portfolios
            alpha_vec = df_mpe.loc[valid_portfolios_in_mpe, 'Mean Pricing Error'].values

            # Number of time periods for which residuals are available
            T = len(df_all_cs_residuals_filtered)

            # Number of portfolios included in the test
            N_portfolios = len(alpha_vec)

            # Check for singularity before inverting
            if np.linalg.det(cov_epsilon) == 0:
                print("\nCovariance matrix of residuals is singular. Cannot compute Chi-square statistic.")
            else:
                inv_cov_epsilon = np.linalg.inv(cov_epsilon)
                chi_square_stat = T * (alpha_vec.T @ inv_cov_epsilon @ alpha_vec)
                df_chi2 = N_portfolios  # Degrees of freedom is the number of portfolios
                p_value_chi2 = 1 - chi2.cdf(chi_square_stat, df_chi2)

                print(f"\nChi-square statistic for joint significance of pricing errors: {chi_square_stat:.4f}")
                print(f"Degrees of Freedom: {df_chi2}")
                print(f"P-value: {p_value_chi2:.4f}")

                if p_value_chi2 < 0.05:
                    print("Conclusion: Reject the null hypothesis that all pricing errors are jointly zero (at 5% significance level).")
                else:
                    print("Conclusion: Fail to reject the null hypothesis that all pricing errors are jointly zero (at 5% significance level).")
        else:
            print("\nNot enough valid cross-sectional residuals to compute Chi-square statistic.")
    except Exception as e:
        print(f"\nError computing Chi-square statistic: {e}")
else:
    print("\nCross-sectional residuals (df_all_cs_residuals) not found or empty. Cannot compute Chi-square statistic.")

Mean Pricing Errors for each portfolio:
  BV_excess_return: 0.4775
  BN_excess_return: 0.0847
  BG_excess_return: -0.0221
  SV_excess_return: -0.0796
  SN_excess_return: 0.2275
  SG_excess_return: -0.1399

Mean Pricing Errors (DataFrame):

                  Mean Pricing Error
Portfolio
BV_excess_return              0.4775
BN_excess_return              0.0847
BG_excess_return             -0.0221
SV_excess_return             -0.0796
SN_excess_return              0.2275
SG_excess_return             -0.1399

Overall Mean Pricing Error across all portfolios: 0.0914

Chi-square statistic for joint significance of pricing errors: -258888400311389504.0000
Degrees of Freedom: 6
P-value: 1.0000
Conclusion: Fail to reject the null hypothesis that all pricing errors are jointly zero (at 5% significance level).